DELETE FROM label WHERE "lang"='spa';
INSERT INTO label VALUES ('BT',1,'spa','De la lista',NULL);
INSERT INTO label VALUES ('BT',2,'spa','Del mapa',NULL);
INSERT INTO label VALUES ('BT',3,'spa','Subir',NULL);
INSERT INTO label VALUES ('BT',4,'spa','Duplicity chcek',NULL);
INSERT INTO label VALUES ('CL',10,'spa','no',NULL);
INSERT INTO label VALUES ('CL',11,'spa','sí',NULL);
INSERT INTO label VALUES ('CL',12,'spa','no',NULL);
INSERT INTO label VALUES ('CL',13,'spa','sí',NULL);
INSERT INTO label VALUES ('CL',201,'spa','creación',NULL);
INSERT INTO label VALUES ('CL',202,'spa','publicación',NULL);
INSERT INTO label VALUES ('CL',203,'spa','revisión',NULL);
INSERT INTO label VALUES ('CL',301,'spa','descargar',NULL);
INSERT INTO label VALUES ('CL',302,'spa','información',NULL);
INSERT INTO label VALUES ('CL',303,'spa','Acceso fuera de línea',NULL);
INSERT INTO label VALUES ('CL',304,'spa','solicitar',NULL);
INSERT INTO label VALUES ('CL',305,'spa','buscar',NULL);
INSERT INTO label VALUES ('CL',401,'spa','Documento digital',NULL);
INSERT INTO label VALUES ('CL',402,'spa','Documento impreso',NULL);
INSERT INTO label VALUES ('CL',403,'spa','Imagen digital',NULL);
INSERT INTO label VALUES ('CL',404,'spa','Imagen impresa',NULL);
INSERT INTO label VALUES ('CL',405,'spa','Mapa digial',NULL);
INSERT INTO label VALUES ('CL',406,'spa','Mapa impreso',NULL);
INSERT INTO label VALUES ('CL',407,'spa','Modelo digital',NULL);
INSERT INTO label VALUES ('CL',408,'spa','Modelo impreso',NULL);
INSERT INTO label VALUES ('CL',409,'spa','Perfil digital',NULL);
INSERT INTO label VALUES ('CL',410,'spa','Perfil impreso',NULL);
INSERT INTO label VALUES ('CL',411,'spa','Tabla digital',NULL);
INSERT INTO label VALUES ('CL',412,'spa','Tabla impresa',NULL);
INSERT INTO label VALUES ('CL',413,'spa','Video digital',NULL);
INSERT INTO label VALUES ('CL',414,'spa','Video grabado',NULL);
INSERT INTO label VALUES ('CL',501,'spa','Sumnistrador del recurso',NULL);
INSERT INTO label VALUES ('CL',502,'spa','responsable/conservador',NULL);
INSERT INTO label VALUES ('CL',503,'spa','propietario',NULL);
INSERT INTO label VALUES ('CL',504,'spa','usuario',NULL);
INSERT INTO label VALUES ('CL',505,'spa','distribuidor',NULL);
INSERT INTO label VALUES ('CL',506,'spa','creador',NULL);
INSERT INTO label VALUES ('CL',507,'spa','Punto de contacto',NULL);
INSERT INTO label VALUES ('CL',508,'spa','Investigador principal',NULL);
INSERT INTO label VALUES ('CL',509,'spa','procesador',NULL);
INSERT INTO label VALUES ('CL',510,'spa','editor',NULL);
INSERT INTO label VALUES ('CL',511,'spa','autor',NULL);
INSERT INTO label VALUES ('CL',601,'spa','Evaluación directa interna',NULL);
INSERT INTO label VALUES ('CL',602,'spa','Evaluación directa externa',NULL);
INSERT INTO label VALUES ('CL',603,'spa','indirecto',NULL);
INSERT INTO label VALUES ('CL',701,'spa','Referencia cruzada',NULL);
INSERT INTO label VALUES ('CL',702,'spa','Mención del trabajo principal',NULL);
INSERT INTO label VALUES ('CL',703,'spa','Parte de una base de datos continua',NULL);
INSERT INTO label VALUES ('CL',704,'spa','fuente',NULL);
INSERT INTO label VALUES ('CL',705,'spa','stereoMate',NULL);
INSERT INTO label VALUES ('CL',801,'spa','campaña',NULL);
INSERT INTO label VALUES ('CL',802,'spa','colección',NULL);
INSERT INTO label VALUES ('CL',803,'spa','ejecución',NULL);
INSERT INTO label VALUES ('CL',804,'spa','experimento',NULL);
INSERT INTO label VALUES ('CL',805,'spa','investigación',NULL);
INSERT INTO label VALUES ('CL',806,'spa','misión',NULL);
INSERT INTO label VALUES ('CL',807,'spa','sensor',NULL);
INSERT INTO label VALUES ('CL',808,'spa','operación',NULL);
INSERT INTO label VALUES ('CL',809,'spa','plataforma',NULL);
INSERT INTO label VALUES ('CL',810,'spa','proceso',NULL);
INSERT INTO label VALUES ('CL',811,'spa','programa',NULL);
INSERT INTO label VALUES ('CL',812,'spa','pryecto',NULL);
INSERT INTO label VALUES ('CL',813,'spa','estudio',NULL);
INSERT INTO label VALUES ('CL',814,'spa','tarea',NULL);
INSERT INTO label VALUES ('CL',815,'spa','test',NULL);
INSERT INTO label VALUES ('CL',901,'spa','punto',NULL);
INSERT INTO label VALUES ('CL',902,'spa','área',NULL);
INSERT INTO label VALUES ('CL',1001,'spa','ucs2',NULL);
INSERT INTO label VALUES ('CL',1002,'spa','ucs4',NULL);
INSERT INTO label VALUES ('CL',1003,'spa','utf7',NULL);
INSERT INTO label VALUES ('CL',1004,'spa','utf8',NULL);
INSERT INTO label VALUES ('CL',1005,'spa','utf16',NULL);
INSERT INTO label VALUES ('CL',1006,'spa','8859part1',NULL);
INSERT INTO label VALUES ('CL',1007,'spa','8859part2',NULL);
INSERT INTO label VALUES ('CL',1008,'spa','8859part3',NULL);
INSERT INTO label VALUES ('CL',1009,'spa','8859part4',NULL);
INSERT INTO label VALUES ('CL',1010,'spa','8859part5',NULL);
INSERT INTO label VALUES ('CL',1011,'spa','8859part6',NULL);
INSERT INTO label VALUES ('CL',1012,'spa','8859part7',NULL);
INSERT INTO label VALUES ('CL',1013,'spa','8859part8',NULL);
INSERT INTO label VALUES ('CL',1014,'spa','8859part9',NULL);
INSERT INTO label VALUES ('CL',1015,'spa','8859part10',NULL);
INSERT INTO label VALUES ('CL',1016,'spa','8859part11',NULL);
INSERT INTO label VALUES ('CL',1018,'spa','8859part13',NULL);
INSERT INTO label VALUES ('CL',1019,'spa','8859part14',NULL);
INSERT INTO label VALUES ('CL',1020,'spa','8859part15',NULL);
INSERT INTO label VALUES ('CL',1021,'spa','8859part16',NULL);
INSERT INTO label VALUES ('CL',1022,'spa','jis',NULL);
INSERT INTO label VALUES ('CL',1023,'spa','shiftJIS',NULL);
INSERT INTO label VALUES ('CL',1024,'spa','eucJP',NULL);
INSERT INTO label VALUES ('CL',1025,'spa','usAscii',NULL);
INSERT INTO label VALUES ('CL',1026,'spa','ebcdic',NULL);
INSERT INTO label VALUES ('CL',1027,'spa','eucKR',NULL);
INSERT INTO label VALUES ('CL',1028,'spa','big5',NULL);
INSERT INTO label VALUES ('CL',1029,'spa','GB2312',NULL);
INSERT INTO label VALUES ('CL',1030,'spa','win-1250',NULL);
INSERT INTO label VALUES ('CL',1031,'spa','CP852',NULL);
INSERT INTO label VALUES ('CL',1101,'spa','desclasificado',NULL);
INSERT INTO label VALUES ('CL',1102,'spa','restringido',NULL);
INSERT INTO label VALUES ('CL',1103,'spa','confidencial',NULL);
INSERT INTO label VALUES ('CL',1104,'spa','secreto',NULL);
INSERT INTO label VALUES ('CL',1105,'spa','alto secreto',NULL);
INSERT INTO label VALUES ('CL',1201,'spa','imagen',NULL);
INSERT INTO label VALUES ('CL',1202,'spa','Clasificación temática',NULL);
INSERT INTO label VALUES ('CL',1203,'spa','medida física',NULL);
INSERT INTO label VALUES ('CL',1301,'spa','clase',NULL);
INSERT INTO label VALUES ('CL',1302,'spa','lista de códigos',NULL);
INSERT INTO label VALUES ('CL',1303,'spa','enumeración',NULL);
INSERT INTO label VALUES ('CL',1304,'spa','Término controlado',NULL);
INSERT INTO label VALUES ('CL',1305,'spa','Clase abstracta',NULL);
INSERT INTO label VALUES ('CL',1306,'spa','Clase agregada',NULL);
INSERT INTO label VALUES ('CL',1307,'spa','Clase específica',NULL);
INSERT INTO label VALUES ('CL',1308,'spa','Clase de datos tipo',NULL);
INSERT INTO label VALUES ('CL',1309,'spa','Clase interface',NULL);
INSERT INTO label VALUES ('CL',1310,'spa','Clase unión',NULL);
INSERT INTO label VALUES ('CL',1311,'spa','Metaclase',NULL);
INSERT INTO label VALUES ('CL',1312,'spa','Clase',NULL);
INSERT INTO label VALUES ('CL',1313,'spa','cadena de caracteres',NULL);
INSERT INTO label VALUES ('CL',1314,'spa','entero',NULL);
INSERT INTO label VALUES ('CL',1315,'spa','asociación',NULL);
INSERT INTO label VALUES ('CL',1401,'spa','fila',NULL);
INSERT INTO label VALUES ('CL',1402,'spa','columna',NULL);
INSERT INTO label VALUES ('CL',1403,'spa','vertical',NULL);
INSERT INTO label VALUES ('CL',1404,'spa','recto',NULL);
INSERT INTO label VALUES ('CL',1405,'spa','perpendicular',NULL);
INSERT INTO label VALUES ('CL',1406,'spa','línea',NULL);
INSERT INTO label VALUES ('CL',1407,'spa','muestra',NULL);
INSERT INTO label VALUES ('CL',1408,'spa','tiempo',NULL);
INSERT INTO label VALUES ('CL',1501,'spa','complejo',NULL);
INSERT INTO label VALUES ('CL',1502,'spa','compuesto',NULL);
INSERT INTO label VALUES ('CL',1503,'spa','curva',NULL);
INSERT INTO label VALUES ('CL',1504,'spa','punto',NULL);
INSERT INTO label VALUES ('CL',1505,'spa','sólido',NULL);
INSERT INTO label VALUES ('CL',1506,'spa','superficie',NULL);
INSERT INTO label VALUES ('CL',1601,'spa','Imagaen borrosa',NULL);
INSERT INTO label VALUES ('CL',1602,'spa','nublado',NULL);
INSERT INTO label VALUES ('CL',1603,'spa','Grado de oblicuidad',NULL);
INSERT INTO label VALUES ('CL',1604,'spa','niebla',NULL);
INSERT INTO label VALUES ('CL',1605,'spa','humo o polvo',NULL);
INSERT INTO label VALUES ('CL',1606,'spa','nocturna',NULL);
INSERT INTO label VALUES ('CL',1607,'spa','lluvioso',NULL);
INSERT INTO label VALUES ('CL',1608,'spa','penumbra',NULL);
INSERT INTO label VALUES ('CL',1609,'spa','sombra',NULL);
INSERT INTO label VALUES ('CL',1610,'spa','nevada',NULL);
INSERT INTO label VALUES ('CL',1611,'spa','zona oculta',NULL);
INSERT INTO label VALUES ('CL',1701,'spa','disciplina',NULL);
INSERT INTO label VALUES ('CL',1702,'spa','localización',NULL);
INSERT INTO label VALUES ('CL',1703,'spa','estrato',NULL);
INSERT INTO label VALUES ('CL',1704,'spa','temporal',NULL);
INSERT INTO label VALUES ('CL',1705,'spa','tema',NULL);
INSERT INTO label VALUES ('CL',1801,'spa','continua',NULL);
INSERT INTO label VALUES ('CL',1802,'spa','diaria',NULL);
INSERT INTO label VALUES ('CL',1803,'spa','semanalmente',NULL);
INSERT INTO label VALUES ('CL',1804,'spa','quincenalmente',NULL);
INSERT INTO label VALUES ('CL',1805,'spa','mensualmente',NULL);
INSERT INTO label VALUES ('CL',1806,'spa','trimestralmente',NULL);
INSERT INTO label VALUES ('CL',1807,'spa','bianuelmente',NULL);
INSERT INTO label VALUES ('CL',1808,'spa','anualmente',NULL);
INSERT INTO label VALUES ('CL',1809,'spa','según necesidad',NULL);
INSERT INTO label VALUES ('CL',1810,'spa','irregular',NULL);
INSERT INTO label VALUES ('CL',1811,'spa','no prevista',NULL);
INSERT INTO label VALUES ('CL',1812,'spa','desconocida',NULL);
INSERT INTO label VALUES ('CL',1901,'spa','cpio',NULL);
INSERT INTO label VALUES ('CL',1902,'spa','tar',NULL);
INSERT INTO label VALUES ('CL',1903,'spa','highSierra',NULL);
INSERT INTO label VALUES ('CL',1904,'spa','iso9660',NULL);
INSERT INTO label VALUES ('CL',1905,'spa','iso9660RockRidge',NULL);
INSERT INTO label VALUES ('CL',1906,'spa','iso9660AppleHFS',NULL);
INSERT INTO label VALUES ('CL',2001,'spa','cdRom',NULL);
INSERT INTO label VALUES ('CL',2002,'spa','dvd',NULL);
INSERT INTO label VALUES ('CL',2003,'spa','dvdRom',NULL);
INSERT INTO label VALUES ('CL',2004,'spa','3halfInchFloppy',NULL);
INSERT INTO label VALUES ('CL',2005,'spa','5quarterInchFloppy',NULL);
INSERT INTO label VALUES ('CL',2006,'spa','7trackTape',NULL);
INSERT INTO label VALUES ('CL',2007,'spa','9trackTape',NULL);
INSERT INTO label VALUES ('CL',2008,'spa','3480Cartridge',NULL);
INSERT INTO label VALUES ('CL',2009,'spa','3490Cartridge',NULL);
INSERT INTO label VALUES ('CL',2010,'spa','3580Cartridge',NULL);
INSERT INTO label VALUES ('CL',2011,'spa','4mmCartridgeTape',NULL);
INSERT INTO label VALUES ('CL',2012,'spa','8mmCartridgeTape',NULL);
INSERT INTO label VALUES ('CL',2013,'spa','1quarterInchCartridgeTape',NULL);
INSERT INTO label VALUES ('CL',2014,'spa','digitalLinearTape',NULL);
INSERT INTO label VALUES ('CL',2015,'spa','en línea',NULL);
INSERT INTO label VALUES ('CL',2016,'spa','satélite',NULL);
INSERT INTO label VALUES ('CL',2017,'spa','línea telefónica',NULL);
INSERT INTO label VALUES ('CL',2018,'spa','impresión',NULL);
INSERT INTO label VALUES ('CL',2101,'spa','obligatorio',NULL);
INSERT INTO label VALUES ('CL',2102,'spa','opcional',NULL);
INSERT INTO label VALUES ('CL',2103,'spa','condicional',NULL);
INSERT INTO label VALUES ('CL',2201,'spa','centro',NULL);
INSERT INTO label VALUES ('CL',2202,'spa','inferior izquierda',NULL);
INSERT INTO label VALUES ('CL',2203,'spa','inferior derecha',NULL);
INSERT INTO label VALUES ('CL',2204,'spa','superior derecha',NULL);
INSERT INTO label VALUES ('CL',2205,'spa','inferior derecha',NULL);
INSERT INTO label VALUES ('CL',2301,'spa','completo',NULL);
INSERT INTO label VALUES ('CL',2302,'spa','histórico / archivo',NULL);
INSERT INTO label VALUES ('CL',2303,'spa','obsoleto',NULL);
INSERT INTO label VALUES ('CL',2304,'spa','en desarrollo',NULL);
INSERT INTO label VALUES ('CL',2305,'spa','previsito',NULL);
INSERT INTO label VALUES ('CL',2306,'spa','requerido',NULL);
INSERT INTO label VALUES ('CL',2307,'spa','en desarrollo',NULL);
INSERT INTO label VALUES ('CL',2401,'spa','derechos de copia',NULL);
INSERT INTO label VALUES ('CL',2402,'spa','patente',NULL);
INSERT INTO label VALUES ('CL',2403,'spa','pendiente de patente',NULL);
INSERT INTO label VALUES ('CL',2404,'spa','marca (comercial)',NULL);
INSERT INTO label VALUES ('CL',2405,'spa','licencia',NULL);
INSERT INTO label VALUES ('CL',2406,'spa','Derechos de la propiedad intelectual',NULL);
INSERT INTO label VALUES ('CL',2407,'spa','restringido',NULL);
INSERT INTO label VALUES ('CL',2408,'spa','Otras restricciones',NULL);
INSERT INTO label VALUES ('CL',2501,'spa','atributo',NULL);
INSERT INTO label VALUES ('CL',2502,'spa','Tipo de atributo',NULL);
INSERT INTO label VALUES ('CL',2503,'spa','hardware de captura',NULL);
INSERT INTO label VALUES ('CL',2504,'spa','Sesión de captura',NULL);
INSERT INTO label VALUES ('CL',2505,'spa','conjunto de datos',NULL);
INSERT INTO label VALUES ('CL',2506,'spa','serie',NULL);
INSERT INTO label VALUES ('CL',2507,'spa','datos no geográficos',NULL);
INSERT INTO label VALUES ('CL',2508,'spa','grupo de dimensiones',NULL);
INSERT INTO label VALUES ('CL',2509,'spa','fenómeno',NULL);
INSERT INTO label VALUES ('CL',2510,'spa','Fenómeno',NULL);
INSERT INTO label VALUES ('CL',2511,'spa','Propiedad',NULL);
INSERT INTO label VALUES ('CL',2512,'spa','Sesión de campo',NULL);
INSERT INTO label VALUES ('CL',2513,'spa','aplicación',NULL);
INSERT INTO label VALUES ('CL',2514,'spa','servicio',NULL);
INSERT INTO label VALUES ('CL',2515,'spa','modelo',NULL);
INSERT INTO label VALUES ('CL',2516,'spa','celda',NULL);
INSERT INTO label VALUES ('CL',2517,'spa','aplicación',NULL);
INSERT INTO label VALUES ('CL',2601,'spa','vector',NULL);
INSERT INTO label VALUES ('CL',2602,'spa','malla',NULL);
INSERT INTO label VALUES ('CL',2603,'spa','Tabla de texto',NULL);
INSERT INTO label VALUES ('CL',2604,'spa','red de triangulos',NULL);
INSERT INTO label VALUES ('CL',2605,'spa','stereoModel',NULL);
INSERT INTO label VALUES ('CL',2606,'spa','video',NULL);
INSERT INTO label VALUES ('CL',2701,'spa','granja',NULL);
INSERT INTO label VALUES ('CL',2702,'spa','biota',NULL);
INSERT INTO label VALUES ('CL',2703,'spa','límites',NULL);
INSERT INTO label VALUES ('CL',2704,'spa','Climatología, meteorología, atmósfera',NULL);
INSERT INTO label VALUES ('CL',2705,'spa','economía',NULL);
INSERT INTO label VALUES ('CL',2706,'spa','relieve',NULL);
INSERT INTO label VALUES ('CL',2707,'spa','medio ambiente',NULL);
INSERT INTO label VALUES ('CL',2708,'spa','Información geocientífica',NULL);
INSERT INTO label VALUES ('CL',2709,'spa','salud',NULL);
INSERT INTO label VALUES ('CL',2710,'spa','cobertura de la Tierra con mapas básicos e imágenes',NULL);
INSERT INTO label VALUES ('CL',2711,'spa','Inteligencia, ejército',NULL);
INSERT INTO label VALUES ('CL',2712,'spa','Aguas interiores',NULL);
INSERT INTO label VALUES ('CL',2713,'spa','localización',NULL);
INSERT INTO label VALUES ('CL',2714,'spa','océanos',NULL);
INSERT INTO label VALUES ('CL',2715,'spa','Planificación, catastro',NULL);
INSERT INTO label VALUES ('CL',2716,'spa','sociedad',NULL);
INSERT INTO label VALUES ('CL',2717,'spa','estructuras',NULL);
INSERT INTO label VALUES ('CL',2718,'spa','transporte',NULL);
INSERT INTO label VALUES ('CL',2719,'spa','Servicios, comunicaciones',NULL);
INSERT INTO label VALUES ('CL',2801,'spa','Solo geometría',NULL);
INSERT INTO label VALUES ('CL',2802,'spa','topología 1D',NULL);
INSERT INTO label VALUES ('CL',2803,'spa','Grafo planar',NULL);
INSERT INTO label VALUES ('CL',2804,'spa','Grafo planar completo',NULL);
INSERT INTO label VALUES ('CL',2805,'spa','Grafo de superficies',NULL);
INSERT INTO label VALUES ('CL',2806,'spa','superficie completa',NULL);
INSERT INTO label VALUES ('CL',2807,'spa','topología 3D',NULL);
INSERT INTO label VALUES ('CL',2808,'spa','Topología completa 3D',NULL);
INSERT INTO label VALUES ('CL',2809,'spa','Abstracta',NULL);
INSERT INTO label VALUES ('CL',3570,'spa','kilómetro',NULL);
INSERT INTO label VALUES ('CL',3571,'spa','metro',NULL);
INSERT INTO label VALUES ('CL',3572,'spa','decímetro',NULL);
INSERT INTO label VALUES ('CL',3573,'spa','milla',NULL);
INSERT INTO label VALUES ('CL',3574,'spa','yarda',NULL);
INSERT INTO label VALUES ('CL',3575,'spa','pie',NULL);
INSERT INTO label VALUES ('CL',3576,'spa','nanómetro',NULL);
INSERT INTO label VALUES ('CL',3577,'spa','micrómetro',NULL);
INSERT INTO label VALUES ('CL',30001,'spa','Descubrimiento',NULL);
INSERT INTO label VALUES ('CL',30002,'spa','Vista',NULL);
INSERT INTO label VALUES ('CL',30003,'spa','Descarga',NULL);
INSERT INTO label VALUES ('CL',30004,'spa','Transformación',NULL);
INSERT INTO label VALUES ('CL',30005,'spa','Invocar',NULL);
INSERT INTO label VALUES ('CL',30006,'spa','Otro',NULL);
INSERT INTO label VALUES ('CL',30101,'spa','Java',NULL);
INSERT INTO label VALUES ('CL',30102,'spa','Corba',NULL);
INSERT INTO label VALUES ('CL',30103,'spa','XML',NULL);
INSERT INTO label VALUES ('CL',30104,'spa','COM',NULL);
INSERT INTO label VALUES ('CL',30105,'spa','SQL',NULL);
INSERT INTO label VALUES ('CL',30106,'spa','Servicios Web',NULL);
INSERT INTO label VALUES ('CL',30211,'spa','suelto',NULL);
INSERT INTO label VALUES ('CL',30212,'spa','mixto',NULL);
INSERT INTO label VALUES ('CL',30213,'spa','compacto',NULL);
INSERT INTO label VALUES ('CL',50131,'spa','grados',NULL);
INSERT INTO label VALUES ('CL',50132,'spa','minutos',NULL);
INSERT INTO label VALUES ('CL',50133,'spa','segundos',NULL);
INSERT INTO label VALUES ('CL',50134,'spa','redianes',NULL);
INSERT INTO label VALUES ('CL',50211,'spa','segundo',NULL);
INSERT INTO label VALUES ('CL',50212,'spa','minuto',NULL);
INSERT INTO label VALUES ('CL',50213,'spa','hora',NULL);
INSERT INTO label VALUES ('CL',50214,'spa','día',NULL);
INSERT INTO label VALUES ('CL',50215,'spa','semana',NULL);
INSERT INTO label VALUES ('CL',50216,'spa','mes',NULL);
INSERT INTO label VALUES ('CL',50217,'spa','año',NULL);
INSERT INTO label VALUES ('CL',63001,'spa','Afar',NULL);
INSERT INTO label VALUES ('CL',63002,'spa','Abkhazian',NULL);
INSERT INTO label VALUES ('CL',63003,'spa','Achinese',NULL);
INSERT INTO label VALUES ('CL',63004,'spa','Acoli',NULL);
INSERT INTO label VALUES ('CL',63005,'spa','Adangme',NULL);
INSERT INTO label VALUES ('CL',63006,'spa','Afro-Asiatic',NULL);
INSERT INTO label VALUES ('CL',63007,'spa','Afrihili',NULL);
INSERT INTO label VALUES ('CL',63008,'spa','Afrikaans',NULL);
INSERT INTO label VALUES ('CL',63009,'spa','Akan',NULL);
INSERT INTO label VALUES ('CL',63010,'spa','Akkadian',NULL);
INSERT INTO label VALUES ('CL',63011,'spa','Albanian',NULL);
INSERT INTO label VALUES ('CL',63012,'spa','Aleut',NULL);
INSERT INTO label VALUES ('CL',63013,'spa','Algonquian languages',NULL);
INSERT INTO label VALUES ('CL',63014,'spa','Amharic',NULL);
INSERT INTO label VALUES ('CL',63015,'spa','English, Old',NULL);
INSERT INTO label VALUES ('CL',63016,'spa','Apache languages',NULL);
INSERT INTO label VALUES ('CL',63017,'spa','Arabic',NULL);
INSERT INTO label VALUES ('CL',63018,'spa','Aramaic',NULL);
INSERT INTO label VALUES ('CL',63019,'spa','Armenian',NULL);
INSERT INTO label VALUES ('CL',63020,'spa','Araucanian',NULL);
INSERT INTO label VALUES ('CL',63021,'spa','Arapaho',NULL);
INSERT INTO label VALUES ('CL',63022,'spa','Artificial (Other)',NULL);
INSERT INTO label VALUES ('CL',63023,'spa','Arawak',NULL);
INSERT INTO label VALUES ('CL',63024,'spa','Assamese',NULL);
INSERT INTO label VALUES ('CL',63025,'spa','Astrurian',NULL);
INSERT INTO label VALUES ('CL',63026,'spa','Athapascan languages',NULL);
INSERT INTO label VALUES ('CL',63027,'spa','Australian languages',NULL);
INSERT INTO label VALUES ('CL',63028,'spa','Avaric',NULL);
INSERT INTO label VALUES ('CL',63029,'spa','Avestan',NULL);
INSERT INTO label VALUES ('CL',63030,'spa','Awadhi',NULL);
INSERT INTO label VALUES ('CL',63031,'spa','Aymara',NULL);
INSERT INTO label VALUES ('CL',63032,'spa','Azerbaijani',NULL);
INSERT INTO label VALUES ('CL',63033,'spa','Banda',NULL);
INSERT INTO label VALUES ('CL',63034,'spa','Bamileke languages',NULL);
INSERT INTO label VALUES ('CL',63035,'spa','Bashkir',NULL);
INSERT INTO label VALUES ('CL',63036,'spa','Baluchi',NULL);
INSERT INTO label VALUES ('CL',63037,'spa','Bambara',NULL);
INSERT INTO label VALUES ('CL',63038,'spa','Balinese',NULL);
INSERT INTO label VALUES ('CL',63039,'spa','Vasco',NULL);
INSERT INTO label VALUES ('CL',63040,'spa','Baltic (Other)',NULL);
INSERT INTO label VALUES ('CL',63041,'spa','Beja',NULL);
INSERT INTO label VALUES ('CL',63042,'spa','Belarusian',NULL);
INSERT INTO label VALUES ('CL',63043,'spa','Bemba',NULL);
INSERT INTO label VALUES ('CL',63044,'spa','Bengali',NULL);
INSERT INTO label VALUES ('CL',63045,'spa','Berber (Other)',NULL);
INSERT INTO label VALUES ('CL',63046,'spa','Bhojpuri',NULL);
INSERT INTO label VALUES ('CL',63047,'spa','Bihari',NULL);
INSERT INTO label VALUES ('CL',63048,'spa','Bikol',NULL);
INSERT INTO label VALUES ('CL',63049,'spa','Bini',NULL);
INSERT INTO label VALUES ('CL',63050,'spa','Bislama',NULL);
INSERT INTO label VALUES ('CL',63051,'spa','Siksika',NULL);
INSERT INTO label VALUES ('CL',63052,'spa','Bantu (Other)',NULL);
INSERT INTO label VALUES ('CL',63053,'spa','Bosnian',NULL);
INSERT INTO label VALUES ('CL',63054,'spa','Braj',NULL);
INSERT INTO label VALUES ('CL',63055,'spa','Breton',NULL);
INSERT INTO label VALUES ('CL',63056,'spa','Batak (Indonesia)',NULL);
INSERT INTO label VALUES ('CL',63057,'spa','Buriat',NULL);
INSERT INTO label VALUES ('CL',63058,'spa','Buginese',NULL);
INSERT INTO label VALUES ('CL',63059,'spa','Búlgaro',NULL);
INSERT INTO label VALUES ('CL',63060,'spa','Burmese',NULL);
INSERT INTO label VALUES ('CL',63061,'spa','Caddo',NULL);
INSERT INTO label VALUES ('CL',63062,'spa','Central American Indian (Other)',NULL);
INSERT INTO label VALUES ('CL',63063,'spa','Carib',NULL);
INSERT INTO label VALUES ('CL',63064,'spa','Catalán',NULL);
INSERT INTO label VALUES ('CL',63065,'spa','Caucasian (Other)',NULL);
INSERT INTO label VALUES ('CL',63066,'spa','Cebuano',NULL);
INSERT INTO label VALUES ('CL',63067,'spa','Chamorro',NULL);
INSERT INTO label VALUES ('CL',63068,'spa','Chibcha',NULL);
INSERT INTO label VALUES ('CL',63069,'spa','Chechen',NULL);
INSERT INTO label VALUES ('CL',63070,'spa','Chagatai',NULL);
INSERT INTO label VALUES ('CL',63071,'spa','Chinese',NULL);
INSERT INTO label VALUES ('CL',63072,'spa','Chuukese',NULL);
INSERT INTO label VALUES ('CL',63073,'spa','Mari',NULL);
INSERT INTO label VALUES ('CL',63074,'spa','Chinook jargon',NULL);
INSERT INTO label VALUES ('CL',63075,'spa','Choctaw',NULL);
INSERT INTO label VALUES ('CL',63076,'spa','Chipewyan',NULL);
INSERT INTO label VALUES ('CL',63077,'spa','Cherokee',NULL);
INSERT INTO label VALUES ('CL',63078,'spa','Church Slavic',NULL);
INSERT INTO label VALUES ('CL',63079,'spa','Chuvash',NULL);
INSERT INTO label VALUES ('CL',63080,'spa','Cheyenne',NULL);
INSERT INTO label VALUES ('CL',63081,'spa','Chamic languages',NULL);
INSERT INTO label VALUES ('CL',63082,'spa','Coptic',NULL);
INSERT INTO label VALUES ('CL',63083,'spa','Cornish',NULL);
INSERT INTO label VALUES ('CL',63084,'spa','Corsican',NULL);
INSERT INTO label VALUES ('CL',63085,'spa','Creoles and pidgins, English-based',NULL);
INSERT INTO label VALUES ('CL',63086,'spa','Creoles and pidgins, French-based',NULL);
INSERT INTO label VALUES ('CL',63087,'spa','Creoles and pidgins, Portuguese-based',NULL);
INSERT INTO label VALUES ('CL',63088,'spa','Cree',NULL);
INSERT INTO label VALUES ('CL',63089,'spa','Creoles and pidgins (Other)',NULL);
INSERT INTO label VALUES ('CL',63090,'spa','Cushitic (Other)',NULL);
INSERT INTO label VALUES ('CL',63091,'spa','Checo',NULL);
INSERT INTO label VALUES ('CL',63092,'spa','Dakota',NULL);
INSERT INTO label VALUES ('CL',63093,'spa','Danés',NULL);
INSERT INTO label VALUES ('CL',63094,'spa','Dayak',NULL);
INSERT INTO label VALUES ('CL',63095,'spa','Delaware',NULL);
INSERT INTO label VALUES ('CL',63096,'spa','Slav (Athapascan)',NULL);
INSERT INTO label VALUES ('CL',63097,'spa','Dogrib',NULL);
INSERT INTO label VALUES ('CL',63098,'spa','Dinka',NULL);
INSERT INTO label VALUES ('CL',63099,'spa','Divehi',NULL);
INSERT INTO label VALUES ('CL',63100,'spa','Dogri',NULL);
INSERT INTO label VALUES ('CL',63101,'spa','Dravidian (Other)',NULL);
INSERT INTO label VALUES ('CL',63102,'spa','Duala',NULL);
INSERT INTO label VALUES ('CL',63103,'spa','Dutch, Middle',NULL);
INSERT INTO label VALUES ('CL',63104,'spa','Holandés',NULL);
INSERT INTO label VALUES ('CL',63105,'spa','Dyula',NULL);
INSERT INTO label VALUES ('CL',63106,'spa','Dzongkha',NULL);
INSERT INTO label VALUES ('CL',63107,'spa','Efik',NULL);
INSERT INTO label VALUES ('CL',63108,'spa','Egyptian (Ancient)',NULL);
INSERT INTO label VALUES ('CL',63109,'spa','Ekajuk',NULL);
INSERT INTO label VALUES ('CL',63110,'spa','Elamite',NULL);
INSERT INTO label VALUES ('CL',63111,'spa','Inglés',NULL);
INSERT INTO label VALUES ('CL',63112,'spa','English, Middle',NULL);
INSERT INTO label VALUES ('CL',63113,'spa','Esperanto',NULL);
INSERT INTO label VALUES ('CL',63114,'spa','Estonio',NULL);
INSERT INTO label VALUES ('CL',63115,'spa','Ewe',NULL);
INSERT INTO label VALUES ('CL',63116,'spa','Ewondo',NULL);
INSERT INTO label VALUES ('CL',63117,'spa','Fang',NULL);
INSERT INTO label VALUES ('CL',63118,'spa','Faeroese',NULL);
INSERT INTO label VALUES ('CL',63119,'spa','Fanti',NULL);
INSERT INTO label VALUES ('CL',63120,'spa','Finlandes',NULL);
INSERT INTO label VALUES ('CL',63121,'spa','Fino-Ugrian (Other)',NULL);
INSERT INTO label VALUES ('CL',63122,'spa','Fon',NULL);
INSERT INTO label VALUES ('CL',63123,'spa','Francés',NULL);
INSERT INTO label VALUES ('CL',63124,'spa','French, Middle',NULL);
INSERT INTO label VALUES ('CL',63125,'spa','French, Old',NULL);
INSERT INTO label VALUES ('CL',63126,'spa','Frisian',NULL);
INSERT INTO label VALUES ('CL',63127,'spa','Fulah',NULL);
INSERT INTO label VALUES ('CL',63128,'spa','Friulian',NULL);
INSERT INTO label VALUES ('CL',63129,'spa','Ga',NULL);
INSERT INTO label VALUES ('CL',63130,'spa','Gayo',NULL);
INSERT INTO label VALUES ('CL',63131,'spa','Gbaya',NULL);
INSERT INTO label VALUES ('CL',63132,'spa','Germanic (Other)',NULL);
INSERT INTO label VALUES ('CL',63133,'spa','Georgian',NULL);
INSERT INTO label VALUES ('CL',63134,'spa','Alemán',NULL);
INSERT INTO label VALUES ('CL',63135,'spa','Geez',NULL);
INSERT INTO label VALUES ('CL',63136,'spa','Gilbertese',NULL);
INSERT INTO label VALUES ('CL',63137,'spa','Gaélico',NULL);
INSERT INTO label VALUES ('CL',63138,'spa','Irlandés',NULL);
INSERT INTO label VALUES ('CL',63139,'spa','Gallegan',NULL);
INSERT INTO label VALUES ('CL',63140,'spa','Manx',NULL);
INSERT INTO label VALUES ('CL',63141,'spa','German, Middle High',NULL);
INSERT INTO label VALUES ('CL',63142,'spa','German, Old High',NULL);
INSERT INTO label VALUES ('CL',63143,'spa','Gondi',NULL);
INSERT INTO label VALUES ('CL',63144,'spa','Gorontalo',NULL);
INSERT INTO label VALUES ('CL',63145,'spa','Gothic',NULL);
INSERT INTO label VALUES ('CL',63146,'spa','Grebo',NULL);
INSERT INTO label VALUES ('CL',63147,'spa','Greek, Ancient',NULL);
INSERT INTO label VALUES ('CL',63148,'spa','Griego moderno',NULL);
INSERT INTO label VALUES ('CL',63149,'spa','Guarani',NULL);
INSERT INTO label VALUES ('CL',63150,'spa','Gujarati',NULL);
INSERT INTO label VALUES ('CL',63151,'spa','Gwich''in',NULL);
INSERT INTO label VALUES ('CL',63152,'spa','Haida',NULL);
INSERT INTO label VALUES ('CL',63153,'spa','Hausa',NULL);
INSERT INTO label VALUES ('CL',63154,'spa','Hawaiian',NULL);
INSERT INTO label VALUES ('CL',63155,'spa','Hebrew',NULL);
INSERT INTO label VALUES ('CL',63156,'spa','Herero',NULL);
INSERT INTO label VALUES ('CL',63157,'spa','Hiligaynon',NULL);
INSERT INTO label VALUES ('CL',63158,'spa','Himachali',NULL);
INSERT INTO label VALUES ('CL',63159,'spa','Hindi',NULL);
INSERT INTO label VALUES ('CL',63160,'spa','Hittite',NULL);
INSERT INTO label VALUES ('CL',63161,'spa','Hmong',NULL);
INSERT INTO label VALUES ('CL',63162,'spa','Hiri Motu',NULL);
INSERT INTO label VALUES ('CL',63163,'spa','Húngaro',NULL);
INSERT INTO label VALUES ('CL',63164,'spa','Hupa',NULL);
INSERT INTO label VALUES ('CL',63165,'spa','Iban',NULL);
INSERT INTO label VALUES ('CL',63166,'spa','Igbo',NULL);
INSERT INTO label VALUES ('CL',63167,'spa','islandés',NULL);
INSERT INTO label VALUES ('CL',63168,'spa','Ido',NULL);
INSERT INTO label VALUES ('CL',63169,'spa','Ijo',NULL);
INSERT INTO label VALUES ('CL',63170,'spa','Inuktitut',NULL);
INSERT INTO label VALUES ('CL',63171,'spa','Interlingue',NULL);
INSERT INTO label VALUES ('CL',63172,'spa','Iloko',NULL);
INSERT INTO label VALUES ('CL',63173,'spa','Interlingua',NULL);
INSERT INTO label VALUES ('CL',63174,'spa','Indic (Other)',NULL);
INSERT INTO label VALUES ('CL',63175,'spa','Indonesian',NULL);
INSERT INTO label VALUES ('CL',63176,'spa','Indo-European (Other)',NULL);
INSERT INTO label VALUES ('CL',63177,'spa','Inupiaq',NULL);
INSERT INTO label VALUES ('CL',63178,'spa','Iranian (Other)',NULL);
INSERT INTO label VALUES ('CL',63179,'spa','Iroquoian languages',NULL);
INSERT INTO label VALUES ('CL',63180,'spa','Italiano',NULL);
INSERT INTO label VALUES ('CL',63181,'spa','Javanese',NULL);
INSERT INTO label VALUES ('CL',63182,'spa','Japanese',NULL);
INSERT INTO label VALUES ('CL',63183,'spa','Judeo-Persian',NULL);
INSERT INTO label VALUES ('CL',63184,'spa','Judeo-Arabic',NULL);
INSERT INTO label VALUES ('CL',63185,'spa','Kara-Kalpak',NULL);
INSERT INTO label VALUES ('CL',63186,'spa','Kabyle',NULL);
INSERT INTO label VALUES ('CL',63187,'spa','Kachin',NULL);
INSERT INTO label VALUES ('CL',63188,'spa','Kalaallisut',NULL);
INSERT INTO label VALUES ('CL',63189,'spa','Kamba',NULL);
INSERT INTO label VALUES ('CL',63190,'spa','Kannada',NULL);
INSERT INTO label VALUES ('CL',63191,'spa','Karen',NULL);
INSERT INTO label VALUES ('CL',63192,'spa','Kashmiri',NULL);
INSERT INTO label VALUES ('CL',63193,'spa','Kanuri',NULL);
INSERT INTO label VALUES ('CL',63194,'spa','Kawi',NULL);
INSERT INTO label VALUES ('CL',63195,'spa','Kazakh',NULL);
INSERT INTO label VALUES ('CL',63196,'spa','Khasi',NULL);
INSERT INTO label VALUES ('CL',63197,'spa','Khoisan (Other)',NULL);
INSERT INTO label VALUES ('CL',63198,'spa','Khmer',NULL);
INSERT INTO label VALUES ('CL',63199,'spa','Khotanese',NULL);
INSERT INTO label VALUES ('CL',63200,'spa','Kikuyu',NULL);
INSERT INTO label VALUES ('CL',63201,'spa','Kinyarwanda',NULL);
INSERT INTO label VALUES ('CL',63202,'spa','Kirghiz',NULL);
INSERT INTO label VALUES ('CL',63203,'spa','Kimbundu',NULL);
INSERT INTO label VALUES ('CL',63204,'spa','Konkani',NULL);
INSERT INTO label VALUES ('CL',63205,'spa','Komi',NULL);
INSERT INTO label VALUES ('CL',63206,'spa','Kongo',NULL);
INSERT INTO label VALUES ('CL',63207,'spa','Korean',NULL);
INSERT INTO label VALUES ('CL',63208,'spa','Kosraean',NULL);
INSERT INTO label VALUES ('CL',63209,'spa','Kpelle',NULL);
INSERT INTO label VALUES ('CL',63210,'spa','Kru',NULL);
INSERT INTO label VALUES ('CL',63211,'spa','Kurukh',NULL);
INSERT INTO label VALUES ('CL',63212,'spa','Kuanyama',NULL);
INSERT INTO label VALUES ('CL',63213,'spa','Kumyk',NULL);
INSERT INTO label VALUES ('CL',63214,'spa','Kurdish',NULL);
INSERT INTO label VALUES ('CL',63215,'spa','Kutenai',NULL);
INSERT INTO label VALUES ('CL',63216,'spa','Ladino',NULL);
INSERT INTO label VALUES ('CL',63217,'spa','Lahnda',NULL);
INSERT INTO label VALUES ('CL',63218,'spa','Lamba',NULL);
INSERT INTO label VALUES ('CL',63219,'spa','Lao',NULL);
INSERT INTO label VALUES ('CL',63220,'spa','Latin',NULL);
INSERT INTO label VALUES ('CL',63221,'spa','Letonio',NULL);
INSERT INTO label VALUES ('CL',63222,'spa','Lezghian',NULL);
INSERT INTO label VALUES ('CL',63223,'spa','Lingala',NULL);
INSERT INTO label VALUES ('CL',63224,'spa','Lituano',NULL);
INSERT INTO label VALUES ('CL',63225,'spa','Mongo',NULL);
INSERT INTO label VALUES ('CL',63226,'spa','Lozi',NULL);
INSERT INTO label VALUES ('CL',63227,'spa','Luxembourgish',NULL);
INSERT INTO label VALUES ('CL',63228,'spa','Luba-Lulua',NULL);
INSERT INTO label VALUES ('CL',63229,'spa','Luba-Katanga',NULL);
INSERT INTO label VALUES ('CL',63230,'spa','Ganda',NULL);
INSERT INTO label VALUES ('CL',63231,'spa','Luiseno',NULL);
INSERT INTO label VALUES ('CL',63232,'spa','Lunda',NULL);
INSERT INTO label VALUES ('CL',63233,'spa','Lushai',NULL);
INSERT INTO label VALUES ('CL',63234,'spa','Macedonian',NULL);
INSERT INTO label VALUES ('CL',63235,'spa','Madurese',NULL);
INSERT INTO label VALUES ('CL',63236,'spa','Magahi',NULL);
INSERT INTO label VALUES ('CL',63237,'spa','Marshallese',NULL);
INSERT INTO label VALUES ('CL',63238,'spa','Maithili',NULL);
INSERT INTO label VALUES ('CL',63239,'spa','Makasar',NULL);
INSERT INTO label VALUES ('CL',63240,'spa','Malayalam',NULL);
INSERT INTO label VALUES ('CL',63241,'spa','Mandingo',NULL);
INSERT INTO label VALUES ('CL',63242,'spa','Maori',NULL);
INSERT INTO label VALUES ('CL',63243,'spa','Austroneasian',NULL);
INSERT INTO label VALUES ('CL',63244,'spa','Marathi',NULL);
INSERT INTO label VALUES ('CL',63245,'spa','Masai',NULL);
INSERT INTO label VALUES ('CL',63246,'spa','Malay',NULL);
INSERT INTO label VALUES ('CL',63247,'spa','Mandar',NULL);
INSERT INTO label VALUES ('CL',63248,'spa','Mende',NULL);
INSERT INTO label VALUES ('CL',63249,'spa','Irish, Middle',NULL);
INSERT INTO label VALUES ('CL',63250,'spa','Micmac',NULL);
INSERT INTO label VALUES ('CL',63251,'spa','Minangkabau',NULL);
INSERT INTO label VALUES ('CL',63252,'spa','Miscellaneous languages',NULL);
INSERT INTO label VALUES ('CL',63253,'spa','Mon-Khmer (Other)',NULL);
INSERT INTO label VALUES ('CL',63254,'spa','Malagasy',NULL);
INSERT INTO label VALUES ('CL',63255,'spa','Maltés',NULL);
INSERT INTO label VALUES ('CL',63256,'spa','Manchu',NULL);
INSERT INTO label VALUES ('CL',63257,'spa','Manipuri',NULL);
INSERT INTO label VALUES ('CL',63258,'spa','Manobo languages',NULL);
INSERT INTO label VALUES ('CL',63259,'spa','Mohawk',NULL);
INSERT INTO label VALUES ('CL',63260,'spa','Mongolian',NULL);
INSERT INTO label VALUES ('CL',63261,'spa','Mossi',NULL);
INSERT INTO label VALUES ('CL',63262,'spa','Multiple languages',NULL);
INSERT INTO label VALUES ('CL',63263,'spa','Munda languages',NULL);
INSERT INTO label VALUES ('CL',63264,'spa','Creek',NULL);
INSERT INTO label VALUES ('CL',63265,'spa','Marwari',NULL);
INSERT INTO label VALUES ('CL',63266,'spa','Mayan languages',NULL);
INSERT INTO label VALUES ('CL',63267,'spa','Nahuatl',NULL);
INSERT INTO label VALUES ('CL',63268,'spa','North American Indian',NULL);
INSERT INTO label VALUES ('CL',63269,'spa','Nauru',NULL);
INSERT INTO label VALUES ('CL',63270,'spa','Navajo',NULL);
INSERT INTO label VALUES ('CL',63271,'spa','Ndebele, South',NULL);
INSERT INTO label VALUES ('CL',63272,'spa','Ndebele, North',NULL);
INSERT INTO label VALUES ('CL',63273,'spa','Ndonga',NULL);
INSERT INTO label VALUES ('CL',63274,'spa','Low German',NULL);
INSERT INTO label VALUES ('CL',63275,'spa','Nepali',NULL);
INSERT INTO label VALUES ('CL',63276,'spa','Newari',NULL);
INSERT INTO label VALUES ('CL',63277,'spa','Nias',NULL);
INSERT INTO label VALUES ('CL',63278,'spa','Niger-Kordofanian (Other)',NULL);
INSERT INTO label VALUES ('CL',63279,'spa','Niuean',NULL);
INSERT INTO label VALUES ('CL',63280,'spa','Norse, Old',NULL);
INSERT INTO label VALUES ('CL',63281,'spa','Noruego',NULL);
INSERT INTO label VALUES ('CL',63282,'spa','Norwegian Nynorsk',NULL);
INSERT INTO label VALUES ('CL',63283,'spa','Norwewgian Bokmal',NULL);
INSERT INTO label VALUES ('CL',63284,'spa','Sotho, Northern',NULL);
INSERT INTO label VALUES ('CL',63285,'spa','Nubian languages',NULL);
INSERT INTO label VALUES ('CL',63286,'spa','Chichewa',NULL);
INSERT INTO label VALUES ('CL',63287,'spa','Nyamwezi',NULL);
INSERT INTO label VALUES ('CL',63288,'spa','Nyankole',NULL);
INSERT INTO label VALUES ('CL',63289,'spa','Nyoro',NULL);
INSERT INTO label VALUES ('CL',63290,'spa','Nzima',NULL);
INSERT INTO label VALUES ('CL',63291,'spa','Occitan',NULL);
INSERT INTO label VALUES ('CL',63292,'spa','Ojibwa',NULL);
INSERT INTO label VALUES ('CL',63293,'spa','Oriya',NULL);
INSERT INTO label VALUES ('CL',63294,'spa','Oromo',NULL);
INSERT INTO label VALUES ('CL',63295,'spa','Osage',NULL);
INSERT INTO label VALUES ('CL',63296,'spa','Ossetian',NULL);
INSERT INTO label VALUES ('CL',63297,'spa','Turkish, Ottoman',NULL);
INSERT INTO label VALUES ('CL',63298,'spa','Otomian languages',NULL);
INSERT INTO label VALUES ('CL',63299,'spa','Papuan (Other)',NULL);
INSERT INTO label VALUES ('CL',63300,'spa','Pangasinan',NULL);
INSERT INTO label VALUES ('CL',63301,'spa','Pahlavi',NULL);
INSERT INTO label VALUES ('CL',63302,'spa','Pampanga',NULL);
INSERT INTO label VALUES ('CL',63303,'spa','Panjabi',NULL);
INSERT INTO label VALUES ('CL',63304,'spa','Papiamento',NULL);
INSERT INTO label VALUES ('CL',63305,'spa','Palauan',NULL);
INSERT INTO label VALUES ('CL',63306,'spa','Persian, Old',NULL);
INSERT INTO label VALUES ('CL',63307,'spa','Persian',NULL);
INSERT INTO label VALUES ('CL',63308,'spa','Philippine (Other)',NULL);
INSERT INTO label VALUES ('CL',63309,'spa','Phoenician',NULL);
INSERT INTO label VALUES ('CL',63310,'spa','Pali',NULL);
INSERT INTO label VALUES ('CL',63311,'spa','Polaco',NULL);
INSERT INTO label VALUES ('CL',63312,'spa','Pohnpeian',NULL);
INSERT INTO label VALUES ('CL',63313,'spa','Portugués',NULL);
INSERT INTO label VALUES ('CL',63314,'spa','Prakrit languages',NULL);
INSERT INTO label VALUES ('CL',63315,'spa','Provencal, Old',NULL);
INSERT INTO label VALUES ('CL',63316,'spa','Pushto',NULL);
INSERT INTO label VALUES ('CL',63317,'spa','Quechua',NULL);
INSERT INTO label VALUES ('CL',63318,'spa','Rajasthani',NULL);
INSERT INTO label VALUES ('CL',63319,'spa','Rapanui',NULL);
INSERT INTO label VALUES ('CL',63320,'spa','Rarotongan',NULL);
INSERT INTO label VALUES ('CL',63321,'spa','Romance (Other)',NULL);
INSERT INTO label VALUES ('CL',63322,'spa','Raeto-Romance',NULL);
INSERT INTO label VALUES ('CL',63323,'spa','Romany',NULL);
INSERT INTO label VALUES ('CL',63324,'spa','Rumano',NULL);
INSERT INTO label VALUES ('CL',63325,'spa','Rundi',NULL);
INSERT INTO label VALUES ('CL',63326,'spa','Ruos',NULL);
INSERT INTO label VALUES ('CL',63327,'spa','Sandawe',NULL);
INSERT INTO label VALUES ('CL',63328,'spa','Sango',NULL);
INSERT INTO label VALUES ('CL',63329,'spa','Yakut',NULL);
INSERT INTO label VALUES ('CL',63330,'spa','South American Indian (Other)',NULL);
INSERT INTO label VALUES ('CL',63331,'spa','Salishan languages',NULL);
INSERT INTO label VALUES ('CL',63332,'spa','Samaritan Aramaic',NULL);
INSERT INTO label VALUES ('CL',63333,'spa','Sanskrit',NULL);
INSERT INTO label VALUES ('CL',63334,'spa','Sasak',NULL);
INSERT INTO label VALUES ('CL',63335,'spa','Santali',NULL);
INSERT INTO label VALUES ('CL',63336,'spa','Serbio',NULL);
INSERT INTO label VALUES ('CL',63337,'spa','Scots',NULL);
INSERT INTO label VALUES ('CL',63338,'spa','Croata',NULL);
INSERT INTO label VALUES ('CL',63339,'spa','Selkup',NULL);
INSERT INTO label VALUES ('CL',63340,'spa','Semitic (Other)',NULL);
INSERT INTO label VALUES ('CL',63341,'spa','Irish, Old',NULL);
INSERT INTO label VALUES ('CL',63342,'spa','Sign Languages',NULL);
INSERT INTO label VALUES ('CL',63343,'spa','Shan',NULL);
INSERT INTO label VALUES ('CL',63344,'spa','Sidamo',NULL);
INSERT INTO label VALUES ('CL',63345,'spa','Sinhalese',NULL);
INSERT INTO label VALUES ('CL',63346,'spa','Siouan languages',NULL);
INSERT INTO label VALUES ('CL',63347,'spa','Sino-Tibetan (Other)',NULL);
INSERT INTO label VALUES ('CL',63348,'spa','Slavic (Other)',NULL);
INSERT INTO label VALUES ('CL',63349,'spa','Eslovaco',NULL);
INSERT INTO label VALUES ('CL',63350,'spa','Esloveno',NULL);
INSERT INTO label VALUES ('CL',63351,'spa','Southern Sami',NULL);
INSERT INTO label VALUES ('CL',63352,'spa','Northern Sami',NULL);
INSERT INTO label VALUES ('CL',63353,'spa','Sami languages (Other)',NULL);
INSERT INTO label VALUES ('CL',63354,'spa','Lule Sami',NULL);
INSERT INTO label VALUES ('CL',63355,'spa','Inari Sami',NULL);
INSERT INTO label VALUES ('CL',63356,'spa','Samoan',NULL);
INSERT INTO label VALUES ('CL',63357,'spa','Skolt Sami',NULL);
INSERT INTO label VALUES ('CL',63358,'spa','Shona',NULL);
INSERT INTO label VALUES ('CL',63359,'spa','Sindhi',NULL);
INSERT INTO label VALUES ('CL',63360,'spa','Soninke',NULL);
INSERT INTO label VALUES ('CL',63361,'spa','Sogdian',NULL);
INSERT INTO label VALUES ('CL',63362,'spa','Somali',NULL);
INSERT INTO label VALUES ('CL',63363,'spa','Songhai',NULL);
INSERT INTO label VALUES ('CL',63364,'spa','Sotho, Southern',NULL);
INSERT INTO label VALUES ('CL',63365,'spa','Español',NULL);
INSERT INTO label VALUES ('CL',63366,'spa','Sardinian',NULL);
INSERT INTO label VALUES ('CL',63367,'spa','Serer',NULL);
INSERT INTO label VALUES ('CL',63368,'spa','Nilo-Saharan (Other)',NULL);
INSERT INTO label VALUES ('CL',63369,'spa','Swati',NULL);
INSERT INTO label VALUES ('CL',63370,'spa','Sukuma',NULL);
INSERT INTO label VALUES ('CL',63371,'spa','Sundanese',NULL);
INSERT INTO label VALUES ('CL',63372,'spa','Susu',NULL);
INSERT INTO label VALUES ('CL',63373,'spa','Sumerian',NULL);
INSERT INTO label VALUES ('CL',63374,'spa','Swahili',NULL);
INSERT INTO label VALUES ('CL',63375,'spa','Sueco',NULL);
INSERT INTO label VALUES ('CL',63376,'spa','Syriac',NULL);
INSERT INTO label VALUES ('CL',63377,'spa','Tahitian',NULL);
INSERT INTO label VALUES ('CL',63378,'spa','Tai (Other)',NULL);
INSERT INTO label VALUES ('CL',63379,'spa','Tamil',NULL);
INSERT INTO label VALUES ('CL',63380,'spa','Tatar',NULL);
INSERT INTO label VALUES ('CL',63381,'spa','Telugu',NULL);
INSERT INTO label VALUES ('CL',63382,'spa','Timne',NULL);
INSERT INTO label VALUES ('CL',63383,'spa','Tereno',NULL);
INSERT INTO label VALUES ('CL',63384,'spa','Tetum',NULL);
INSERT INTO label VALUES ('CL',63385,'spa','Tajik',NULL);
INSERT INTO label VALUES ('CL',63386,'spa','Tagalog',NULL);
INSERT INTO label VALUES ('CL',63387,'spa','Thai',NULL);
INSERT INTO label VALUES ('CL',63388,'spa','Tibetan',NULL);
INSERT INTO label VALUES ('CL',63389,'spa','Tigre',NULL);
INSERT INTO label VALUES ('CL',63390,'spa','Tigrinya',NULL);
INSERT INTO label VALUES ('CL',63391,'spa','Tiv',NULL);
INSERT INTO label VALUES ('CL',63392,'spa','Tokelau',NULL);
INSERT INTO label VALUES ('CL',63393,'spa','Tlingit',NULL);
INSERT INTO label VALUES ('CL',63394,'spa','Tamashek',NULL);
INSERT INTO label VALUES ('CL',63395,'spa','Tonga (Nyasa)',NULL);
INSERT INTO label VALUES ('CL',63396,'spa','Tonga (Tonga Islands)',NULL);
INSERT INTO label VALUES ('CL',63397,'spa','Tok Pisin',NULL);
INSERT INTO label VALUES ('CL',63398,'spa','Tsimshian',NULL);
INSERT INTO label VALUES ('CL',63399,'spa','Tswana',NULL);
INSERT INTO label VALUES ('CL',63400,'spa','Tsonga',NULL);
INSERT INTO label VALUES ('CL',63401,'spa','Turkmen',NULL);
INSERT INTO label VALUES ('CL',63402,'spa','Tupi languages',NULL);
INSERT INTO label VALUES ('CL',63403,'spa','Turco',NULL);
INSERT INTO label VALUES ('CL',63404,'spa','Altaic (Other)',NULL);
INSERT INTO label VALUES ('CL',63405,'spa','Tuvalu',NULL);
INSERT INTO label VALUES ('CL',63406,'spa','Twi',NULL);
INSERT INTO label VALUES ('CL',63407,'spa','Tuvinian',NULL);
INSERT INTO label VALUES ('CL',63408,'spa','Ugaritic',NULL);
INSERT INTO label VALUES ('CL',63409,'spa','Uighur',NULL);
INSERT INTO label VALUES ('CL',63410,'spa','Ucraniano',NULL);
INSERT INTO label VALUES ('CL',63411,'spa','Umbundu',NULL);
INSERT INTO label VALUES ('CL',63412,'spa','Undetermined',NULL);
INSERT INTO label VALUES ('CL',63413,'spa','Urdu',NULL);
INSERT INTO label VALUES ('CL',63414,'spa','Uzbek',NULL);
INSERT INTO label VALUES ('CL',63415,'spa','Vai',NULL);
INSERT INTO label VALUES ('CL',63416,'spa','Venda',NULL);
INSERT INTO label VALUES ('CL',63417,'spa','Vietnamese',NULL);
INSERT INTO label VALUES ('CL',63418,'spa','Volapuk',NULL);
INSERT INTO label VALUES ('CL',63419,'spa','Votic',NULL);
INSERT INTO label VALUES ('CL',63420,'spa','Wakashan languages',NULL);
INSERT INTO label VALUES ('CL',63421,'spa','Walamo',NULL);
INSERT INTO label VALUES ('CL',63422,'spa','Waray',NULL);
INSERT INTO label VALUES ('CL',63423,'spa','Washo',NULL);
INSERT INTO label VALUES ('CL',63424,'spa','Welsh',NULL);
INSERT INTO label VALUES ('CL',63425,'spa','Sorbian languages',NULL);
INSERT INTO label VALUES ('CL',63426,'spa','Wallon',NULL);
INSERT INTO label VALUES ('CL',63427,'spa','Wolof',NULL);
INSERT INTO label VALUES ('CL',63428,'spa','Xhosa',NULL);
INSERT INTO label VALUES ('CL',63429,'spa','Yao',NULL);
INSERT INTO label VALUES ('CL',63430,'spa','Yapese',NULL);
INSERT INTO label VALUES ('CL',63431,'spa','Yiddish',NULL);
INSERT INTO label VALUES ('CL',63432,'spa','Yoruba',NULL);
INSERT INTO label VALUES ('CL',63433,'spa','Yupik languages',NULL);
INSERT INTO label VALUES ('CL',63434,'spa','Zapotec',NULL);
INSERT INTO label VALUES ('CL',63435,'spa','Zenaga',NULL);
INSERT INTO label VALUES ('CL',63436,'spa','Zhuang',NULL);
INSERT INTO label VALUES ('CL',63437,'spa','Zande',NULL);
INSERT INTO label VALUES ('CL',63438,'spa','Zulu',NULL);
INSERT INTO label VALUES ('CL',63439,'spa','Zuni',NULL);
INSERT INTO label VALUES ('CL',63440,'spa','No linguistic content',NULL);
INSERT INTO label VALUES ('CL',100081,'spa','Colección',NULL);
INSERT INTO label VALUES ('CL',100082,'spa','Conjunto de datos',NULL);
INSERT INTO label VALUES ('CL',100083,'spa','Evento',NULL);
INSERT INTO label VALUES ('CL',100084,'spa','Imagen',NULL);
INSERT INTO label VALUES ('CL',100085,'spa','Recurso Interactivo',NULL);
INSERT INTO label VALUES ('CL',100086,'spa','Imágenes en movimiento',NULL);
INSERT INTO label VALUES ('CL',100087,'spa','Objeto Físico',NULL);
INSERT INTO label VALUES ('CL',100088,'spa','Servicio',NULL);
INSERT INTO label VALUES ('CL',100089,'spa','Software',NULL);
INSERT INTO label VALUES ('CL',100090,'spa','sonido',NULL);
INSERT INTO label VALUES ('CL',100091,'spa','Imagen Estática',NULL);
INSERT INTO label VALUES ('CL',100092,'spa','Texto',NULL);
INSERT INTO label VALUES ('CL',100093,'spa','Proyecto *',NULL);
INSERT INTO label VALUES ('DL',1,'spa','Inglés',NULL);
INSERT INTO label VALUES ('DL',2,'spa','Checo',NULL);
INSERT INTO label VALUES ('DL',3,'spa','Polaco',NULL);
INSERT INTO label VALUES ('EL',1,'spa','INSPIRE profile verification',NULL);
INSERT INTO label VALUES ('EL',10,'spa','Metadatos',NULL);
INSERT INTO label VALUES ('EL',20,'spa','identificador del fichero',NULL);
INSERT INTO label VALUES ('EL',30,'spa','idioma',NULL);
INSERT INTO label VALUES ('EL',31,'spa','Código ISO',NULL);
INSERT INTO label VALUES ('EL',32,'spa','Nombre ISO',NULL);
INSERT INTO label VALUES ('EL',33,'spa','Código del Lenguaje',NULL);
INSERT INTO label VALUES ('EL',40,'spa','Conjunto de caracteres',NULL);
INSERT INTO label VALUES ('EL',41,'spa','MD_CharacterSetCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',42,'spa','MD_CharacterSetCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',50,'spa','Identificador del padre',NULL);
INSERT INTO label VALUES ('EL',60,'spa','Nivel jerárquico',NULL);
INSERT INTO label VALUES ('EL',61,'spa','MD_ScopeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',62,'spa','MD_ScopeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',70,'spa','Nombre del nivel jerárquico',NULL);
INSERT INTO label VALUES ('EL',80,'spa','Responsable de los metadatos',NULL);
INSERT INTO label VALUES ('EL',90,'spa','Fecha de creación',NULL);
INSERT INTO label VALUES ('EL',100,'spa','Nombre del estándar de metadatos',NULL);
INSERT INTO label VALUES ('EL',110,'spa','Versión del estándar de metadatos',NULL);
INSERT INTO label VALUES ('EL',111,'spa','URI del conjunto de datos',NULL);
INSERT INTO label VALUES ('EL',120,'spa','Representación espacial',NULL);
INSERT INTO label VALUES ('EL',130,'spa','Sistema de Referencia',NULL);
INSERT INTO label VALUES ('EL',140,'spa','Extensión de los Metadatos',NULL);
INSERT INTO label VALUES ('EL',150,'spa','Identificación',NULL);
INSERT INTO label VALUES ('EL',160,'spa','Contenido',NULL);
INSERT INTO label VALUES ('EL',170,'spa','Distribución',NULL);
INSERT INTO label VALUES ('EL',180,'spa','Calidad de datos',NULL);
INSERT INTO label VALUES ('EL',190,'spa','Portrayal Catalogue',NULL);
INSERT INTO label VALUES ('EL',200,'spa','Restricciones de los Metadatos',NULL);
INSERT INTO label VALUES ('EL',210,'spa','Esquema de Aplicación',NULL);
INSERT INTO label VALUES ('EL',220,'spa','Mantenimiento de los Metadatos',NULL);
INSERT INTO label VALUES ('EL',230,'spa','identificación',NULL);
INSERT INTO label VALUES ('EL',240,'spa','referencia',NULL);
INSERT INTO label VALUES ('EL',250,'spa','resumen',NULL);
INSERT INTO label VALUES ('EL',260,'spa','objetivo',NULL);
INSERT INTO label VALUES ('EL',270,'spa','créditos',NULL);
INSERT INTO label VALUES ('EL',280,'spa','status',NULL);
INSERT INTO label VALUES ('EL',281,'spa','MD_ProgressCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',282,'spa','MD_ProgressCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',290,'spa','Punto de contacto',NULL);
INSERT INTO label VALUES ('EL',300,'spa','Mantenimiento del Recurso',NULL);
INSERT INTO label VALUES ('EL',310,'spa','Vista previa',NULL);
INSERT INTO label VALUES ('EL',320,'spa','Formato del Recurso',NULL);
INSERT INTO label VALUES ('EL',330,'spa','Descripción de las Palabras Clave ',NULL);
INSERT INTO label VALUES ('EL',340,'spa','Uso Específco del Recurso',NULL);
INSERT INTO label VALUES ('EL',350,'spa','Restricciones del Recurso',NULL);
INSERT INTO label VALUES ('EL',351,'spa','Información de Agregación',NULL);
INSERT INTO label VALUES ('EL',360,'spa','Identificación de los Datos',NULL);
INSERT INTO label VALUES ('EL',370,'spa','Tipo de Representación Espacial',NULL);
INSERT INTO label VALUES ('EL',371,'spa','MD_SpatialRepresentationTypeCodeType',NULL);
INSERT INTO label VALUES ('EL',372,'spa','MD_SpatialRepresentationTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',380,'spa','Resolución Espacial',NULL);
INSERT INTO label VALUES ('EL',390,'spa','idioma',NULL);
INSERT INTO label VALUES ('EL',391,'spa','Código ISO',NULL);
INSERT INTO label VALUES ('EL',392,'spa','Nombre ISO',NULL);
INSERT INTO label VALUES ('EL',393,'spa','Otro idioma',NULL);
INSERT INTO label VALUES ('EL',400,'spa','Conjunto de caracteres',NULL);
INSERT INTO label VALUES ('EL',401,'spa','MD_CharacterSetCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',402,'spa','MD_CharacterSetCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',410,'spa','Categoría',NULL);
INSERT INTO label VALUES ('EL',411,'spa','MD_TopicCategoryCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',412,'spa','MD_TopicCategoryCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',440,'spa','Descripción del Proceso',NULL);
INSERT INTO label VALUES ('EL',450,'spa','Extensión',NULL);
INSERT INTO label VALUES ('EL',460,'spa','Información Adicional',NULL);
INSERT INTO label VALUES ('EL',470,'spa','Identificación del Servicio',NULL);
INSERT INTO label VALUES ('EL',480,'spa','Imagen de los datos',NULL);
INSERT INTO label VALUES ('EL',490,'spa','Nombre del Fichero',NULL);
INSERT INTO label VALUES ('EL',500,'spa','Descripcion del Fichero',NULL);
INSERT INTO label VALUES ('EL',510,'spa','Tipo de fichero',NULL);
INSERT INTO label VALUES ('EL',520,'spa','Palabras clave',NULL);
INSERT INTO label VALUES ('EL',530,'spa','palabra clave',NULL);
INSERT INTO label VALUES ('EL',540,'spa','Tipo',NULL);
INSERT INTO label VALUES ('EL',541,'spa','MD_KeywordTypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',542,'spa','MD_KeywordTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',550,'spa','Nombre del Thesauro',NULL);
INSERT INTO label VALUES ('EL',560,'spa','Fracción representativa',NULL);
INSERT INTO label VALUES ('EL',570,'spa','denominador',NULL);
INSERT INTO label VALUES ('EL',590,'spa','Resolución',NULL);
INSERT INTO label VALUES ('EL',600,'spa','Escala Equivalente',NULL);
INSERT INTO label VALUES ('EL',610,'spa','distancia',NULL);
INSERT INTO label VALUES ('EL',620,'spa','Uso',NULL);
INSERT INTO label VALUES ('EL',630,'spa','Uso específico',NULL);
INSERT INTO label VALUES ('EL',640,'spa','Fecha/Hora de uso',NULL);
INSERT INTO label VALUES ('EL',650,'spa','Limitaciones de uso específicas',NULL);
INSERT INTO label VALUES ('EL',660,'spa','Contacto de atención al usuario',NULL);
INSERT INTO label VALUES ('EL',661,'spa','Información agregada',NULL);
INSERT INTO label VALUES ('EL',662,'spa','Nombre del conjunto de datos agregado',NULL);
INSERT INTO label VALUES ('EL',663,'spa','Identificador del conjunto de datos agragado',NULL);
INSERT INTO label VALUES ('EL',664,'spa','Tipo de asociación',NULL);
INSERT INTO label VALUES ('EL',665,'spa','Tipo de iniciativa',NULL);
INSERT INTO label VALUES ('EL',666,'spa','DS_AssociationTypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',667,'spa','DS_AssociationTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',668,'spa','DS_InitiativeTypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',669,'spa','DS_InitiativeTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',670,'spa','Restriciones',NULL);
INSERT INTO label VALUES ('EL',680,'spa','Limitaciones de uso',NULL);
INSERT INTO label VALUES ('EL',690,'spa','MD_LegalConstraints',NULL);
INSERT INTO label VALUES ('EL',700,'spa','Restricciones de acceso',NULL);
INSERT INTO label VALUES ('EL',701,'spa','MD_RestrictionCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',702,'spa','MD_RestrictionCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',710,'spa','Restricciones de uso',NULL);
INSERT INTO label VALUES ('EL',711,'spa','MD_RestrictionCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',712,'spa','MD_RestrictionCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',720,'spa','Otras restricciones',NULL);
INSERT INTO label VALUES ('EL',730,'spa','MD_SecurityConstraints',NULL);
INSERT INTO label VALUES ('EL',740,'spa','clasificación',NULL);
INSERT INTO label VALUES ('EL',741,'spa','MD_ClassificationCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',742,'spa','MD_ClassificationCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',750,'spa','Observaciones',NULL);
INSERT INTO label VALUES ('EL',760,'spa','Sistema de clasificación',NULL);
INSERT INTO label VALUES ('EL',770,'spa','handlingDescription',NULL);
INSERT INTO label VALUES ('EL',780,'spa','Calidad de los datos',NULL);
INSERT INTO label VALUES ('EL',790,'spa','Ámbito',NULL);
INSERT INTO label VALUES ('EL',800,'spa','Informe',NULL);
INSERT INTO label VALUES ('EL',810,'spa','Linaje',NULL);
INSERT INTO label VALUES ('EL',820,'spa','LI_Lineage',NULL);
INSERT INTO label VALUES ('EL',830,'spa','declaración',NULL);
INSERT INTO label VALUES ('EL',840,'spa','Pasos del proceso',NULL);
INSERT INTO label VALUES ('EL',850,'spa','Origen de los datos',NULL);
INSERT INTO label VALUES ('EL',860,'spa','LI_ProcessStep',NULL);
INSERT INTO label VALUES ('EL',870,'spa','descripción',NULL);
INSERT INTO label VALUES ('EL',880,'spa','rationale',NULL);
INSERT INTO label VALUES ('EL',890,'spa','Fecha-Hora',NULL);
INSERT INTO label VALUES ('EL',900,'spa','responsable',NULL);
INSERT INTO label VALUES ('EL',910,'spa','Origen de los datos',NULL);
INSERT INTO label VALUES ('EL',920,'spa','LI_Source',NULL);
INSERT INTO label VALUES ('EL',930,'spa','Descripción',NULL);
INSERT INTO label VALUES ('EL',940,'spa','Denominador de la escala',NULL);
INSERT INTO label VALUES ('EL',950,'spa','Sistema de Referencia original',NULL);
INSERT INTO label VALUES ('EL',960,'spa','referencias de la fuente',NULL);
INSERT INTO label VALUES ('EL',970,'spa','Extensión de la fuente',NULL);
INSERT INTO label VALUES ('EL',980,'spa','Proceso de la fuente',NULL);
INSERT INTO label VALUES ('EL',990,'spa','DQ_Element',NULL);
INSERT INTO label VALUES ('EL',1000,'spa','Nombre de la medida',NULL);
INSERT INTO label VALUES ('EL',1010,'spa','Idnetificación de la medida',NULL);
INSERT INTO label VALUES ('EL',1020,'spa','Descricpión de la medida',NULL);
INSERT INTO label VALUES ('EL',1030,'spa','Tipo de método de evaluación',NULL);
INSERT INTO label VALUES ('EL',1031,'spa','DQ_EvaluationMethodTypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',1032,'spa','DQ_EvaluationMethodTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',1040,'spa','Descripción del método de evaluación',NULL);
INSERT INTO label VALUES ('EL',1050,'spa','Procedimiento de evaluación',NULL);
INSERT INTO label VALUES ('EL',1060,'spa','Fecha-Hora',NULL);
INSERT INTO label VALUES ('EL',1070,'spa','Resultado',NULL);
INSERT INTO label VALUES ('EL',1080,'spa','Completitud',NULL);
INSERT INTO label VALUES ('EL',1090,'spa','Completitud por Comisión',NULL);
INSERT INTO label VALUES ('EL',1100,'spa','Completitud por Omisión',NULL);
INSERT INTO label VALUES ('EL',1110,'spa','Consistencia Lógica',NULL);
INSERT INTO label VALUES ('EL',1120,'spa','Consistencia Conceptual',NULL);
INSERT INTO label VALUES ('EL',1130,'spa','Consistencia de Dominio',NULL);
INSERT INTO label VALUES ('EL',1140,'spa','Consistencia de Formato',NULL);
INSERT INTO label VALUES ('EL',1150,'spa','Consistencia Topoógica',NULL);
INSERT INTO label VALUES ('EL',1160,'spa','Exactitud Posicional',NULL);
INSERT INTO label VALUES ('EL',1170,'spa','Exactitud Posicional Externa Absoluta',NULL);
INSERT INTO label VALUES ('EL',1180,'spa','Exactitud Posicional de Datos de Malla',NULL);
INSERT INTO label VALUES ('EL',1190,'spa','Exactitud Posicional Interna Relativa',NULL);
INSERT INTO label VALUES ('EL',1200,'spa','Exactitud Temporal',NULL);
INSERT INTO label VALUES ('EL',1210,'spa','Exactitud de una Medida de Tiempo',NULL);
INSERT INTO label VALUES ('EL',1220,'spa','Consistencia temporal',NULL);
INSERT INTO label VALUES ('EL',1230,'spa','Validez temporal',NULL);
INSERT INTO label VALUES ('EL',1240,'spa','Exactitud Temática',NULL);
INSERT INTO label VALUES ('EL',1250,'spa','Corrección de la Clasificación Temática',NULL);
INSERT INTO label VALUES ('EL',1260,'spa','Exactitud de los atributos no cuantitativos',NULL);
INSERT INTO label VALUES ('EL',1270,'spa','Exactitud de los atributos cuantitativos',NULL);
INSERT INTO label VALUES ('EL',1280,'spa','Resultado',NULL);
INSERT INTO label VALUES ('EL',1290,'spa','Conformidad del resultado',NULL);
INSERT INTO label VALUES ('EL',1300,'spa','especificación',NULL);
INSERT INTO label VALUES ('EL',1310,'spa','explicación',NULL);
INSERT INTO label VALUES ('EL',1320,'spa','Conformidad del resultado',NULL);
INSERT INTO label VALUES ('EL',1330,'spa','DQ_QuantitativeResult',NULL);
INSERT INTO label VALUES ('EL',1340,'spa','Tipo de valor',NULL);
INSERT INTO label VALUES ('EL',1350,'spa','Unidad de medida',NULL);
INSERT INTO label VALUES ('EL',1351,'spa','Unidad de medida angular',NULL);
INSERT INTO label VALUES ('EL',1352,'spa','Unidad de medida de superficie',NULL);
INSERT INTO label VALUES ('EL',1353,'spa','Unidad de medida de longitud',NULL);
INSERT INTO label VALUES ('EL',1354,'spa','Unidad de medida de escala',NULL);
INSERT INTO label VALUES ('EL',1355,'spa','Unidad de medida de tiempo',NULL);
INSERT INTO label VALUES ('EL',1356,'spa','Unidad de medida de veolocidad',NULL);
INSERT INTO label VALUES ('EL',1357,'spa','Unidad de medida de volumen',NULL);
INSERT INTO label VALUES ('EL',1360,'spa','Error estadístico',NULL);
INSERT INTO label VALUES ('EL',1370,'spa','valor',NULL);
INSERT INTO label VALUES ('EL',1380,'spa','DQ_Scope',NULL);
INSERT INTO label VALUES ('EL',1390,'spa','nivel',NULL);
INSERT INTO label VALUES ('EL',1400,'spa','ámbito',NULL);
INSERT INTO label VALUES ('EL',1410,'spa','Descripción del nivel de datos',NULL);
INSERT INTO label VALUES ('EL',1420,'spa','MD_MaintenanceInformation',NULL);
INSERT INTO label VALUES ('EL',1425,'spa','MD_MaintenanceInformation',NULL);
INSERT INTO label VALUES ('EL',1430,'spa','frecuencia de actualización / mantenimiento',NULL);
INSERT INTO label VALUES ('EL',1431,'spa','MD_MaintenanceFrequencyCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',1432,'spa','MD_MaintenanceFrequencyCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',1440,'spa','Fecha de la siguiente actualización',NULL);
INSERT INTO label VALUES ('EL',1450,'spa','Otro periodo de mantenimiento',NULL);
INSERT INTO label VALUES ('EL',1460,'spa','Ámbito de mantenimiento',NULL);
INSERT INTO label VALUES ('EL',1461,'spa','MD_ScopeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',1462,'spa','MD_ScopeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',1470,'spa','Descripción del ámbito de actualización',NULL);
INSERT INTO label VALUES ('EL',1480,'spa','Observaciones sobre el mantenimiento',NULL);
INSERT INTO label VALUES ('EL',1481,'spa','contacto',NULL);
INSERT INTO label VALUES ('EL',1490,'spa','MD_ScopeDescription',NULL);
INSERT INTO label VALUES ('EL',1500,'spa','atributos',NULL);
INSERT INTO label VALUES ('EL',1510,'spa','fenómenos',NULL);
INSERT INTO label VALUES ('EL',1520,'spa','Instancias de fenómenos',NULL);
INSERT INTO label VALUES ('EL',1530,'spa','Instancias de atributos',NULL);
INSERT INTO label VALUES ('EL',1540,'spa','Conjunto de datos',NULL);
INSERT INTO label VALUES ('EL',1550,'spa','Otro',NULL);
INSERT INTO label VALUES ('EL',1560,'spa','MD_SpatialRepresentation',NULL);
INSERT INTO label VALUES ('EL',1570,'spa','Representación espacial en malla',NULL);
INSERT INTO label VALUES ('EL',1580,'spa','Número de dimensiones',NULL);
INSERT INTO label VALUES ('EL',1590,'spa','Propiedades de los ejes',NULL);
INSERT INTO label VALUES ('EL',1600,'spa','Geometría reticular',NULL);
INSERT INTO label VALUES ('EL',1601,'spa','MD_CellGeometryCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',1602,'spa','MD_CellGeometryCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',1610,'spa','Disponibilidad de parámetros de transformación',NULL);
INSERT INTO label VALUES ('EL',1620,'spa','MD_Georectified',NULL);
INSERT INTO label VALUES ('EL',1630,'spa','Disponibilidad de puntos de verificación',NULL);
INSERT INTO label VALUES ('EL',1640,'spa','Descripción de los puntos de verificación',NULL);
INSERT INTO label VALUES ('EL',1650,'spa','Puntos de las esquinas',NULL);
INSERT INTO label VALUES ('EL',1660,'spa','Punto central',NULL);
INSERT INTO label VALUES ('EL',1670,'spa','Punto del pixel',NULL);
INSERT INTO label VALUES ('EL',1680,'spa','Descripción de las diemnsiones de tranformación',NULL);
INSERT INTO label VALUES ('EL',1690,'spa','Correspondencia de las dimensiones de transformación',NULL);
INSERT INTO label VALUES ('EL',1700,'spa','MD_Georeferenceable',NULL);
INSERT INTO label VALUES ('EL',1710,'spa','Disponibilidad de puntos de control',NULL);
INSERT INTO label VALUES ('EL',1720,'spa','Disponibilidad de parámetros de orientación',NULL);
INSERT INTO label VALUES ('EL',1730,'spa','Descripción de los parámetros de orientación',NULL);
INSERT INTO label VALUES ('EL',1740,'spa','Parámetros de georreferenciación',NULL);
INSERT INTO label VALUES ('EL',1750,'spa','Referencias de los parámetros',NULL);
INSERT INTO label VALUES ('EL',1760,'spa','Representación Espacial Vectorial',NULL);
INSERT INTO label VALUES ('EL',1770,'spa','Nivel topológico',NULL);
INSERT INTO label VALUES ('EL',1771,'spa','MD_TopologyLevelCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',1772,'spa','MD_TopologyLevelCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',1780,'spa','Objetos geométricos',NULL);
INSERT INTO label VALUES ('EL',1790,'spa','Dimensión',NULL);
INSERT INTO label VALUES ('EL',1800,'spa','Denominación de la dimensión',NULL);
INSERT INTO label VALUES ('EL',1801,'spa','MD_DimensionNameTypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',1802,'spa','MD_DimensionNameTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',1810,'spa','Tamaño del eje',NULL);
INSERT INTO label VALUES ('EL',1820,'spa','resolución',NULL);
INSERT INTO label VALUES ('EL',1830,'spa','MD_GeometricObjects',NULL);
INSERT INTO label VALUES ('EL',1840,'spa','Tipo de objeto geométrico',NULL);
INSERT INTO label VALUES ('EL',1841,'spa','MD_GeometricObjectTypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',1842,'spa','MD_GeometricObjectTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',1850,'spa','Número de objetos espaciales',NULL);
INSERT INTO label VALUES ('EL',1860,'spa','MD_ReferenceSystem',NULL);
INSERT INTO label VALUES ('EL',1870,'spa','Identificado del sistema de referencia',NULL);
INSERT INTO label VALUES ('EL',1890,'spa','SRC',NULL);
INSERT INTO label VALUES ('EL',1900,'spa','proyección',NULL);
INSERT INTO label VALUES ('EL',1910,'spa','elipsoide',NULL);
INSERT INTO label VALUES ('EL',1920,'spa','Datum',NULL);
INSERT INTO label VALUES ('EL',1930,'spa','Parámetros del elipsoide',NULL);
INSERT INTO label VALUES ('EL',1940,'spa','Parámetros de la proyección',NULL);
INSERT INTO label VALUES ('EL',1950,'spa','RS_ReferenceSystem',NULL);
INSERT INTO label VALUES ('EL',1960,'spa','nombre',NULL);
INSERT INTO label VALUES ('EL',1970,'spa','Ámbito de validez',NULL);
INSERT INTO label VALUES ('EL',2010,'spa','MD_EllipsoidParameters',NULL);
INSERT INTO label VALUES ('EL',2020,'spa','semieje mayor',NULL);
INSERT INTO label VALUES ('EL',2030,'spa','Unidades del eje',NULL);
INSERT INTO label VALUES ('EL',2040,'spa','denominador del factor de aplanamiento',NULL);
INSERT INTO label VALUES ('EL',2050,'spa','identificador',NULL);
INSERT INTO label VALUES ('EL',2060,'spa','responsable',NULL);
INSERT INTO label VALUES ('EL',2070,'spa','código',NULL);
INSERT INTO label VALUES ('EL',2080,'spa','RS_Identifier',NULL);
INSERT INTO label VALUES ('EL',2081,'spa','Código del sitio',NULL);
INSERT INTO label VALUES ('EL',2082,'spa','versión',NULL);
INSERT INTO label VALUES ('EL',2090,'spa','MD_ObliqueLineAzimuth',NULL);
INSERT INTO label VALUES ('EL',2100,'spa','Ánguo de azimuth',NULL);
INSERT INTO label VALUES ('EL',2110,'spa','Longitud del origen de la proyección',NULL);
INSERT INTO label VALUES ('EL',2120,'spa','MD_ObliqueLinePoint',NULL);
INSERT INTO label VALUES ('EL',2130,'spa','Latitud de la línea oblicua',NULL);
INSERT INTO label VALUES ('EL',2140,'spa','Longitud de la línea oblicua',NULL);
INSERT INTO label VALUES ('EL',2150,'spa','MD_ProjectionParameters',NULL);
INSERT INTO label VALUES ('EL',2160,'spa','zona',NULL);
INSERT INTO label VALUES ('EL',2170,'spa','Paralelo estándar',NULL);
INSERT INTO label VALUES ('EL',2180,'spa','Longitud en el meridiano central',NULL);
INSERT INTO label VALUES ('EL',2190,'spa','Latitud en el origen de la proyección',NULL);
INSERT INTO label VALUES ('EL',2200,'spa','Falso Este',NULL);
INSERT INTO label VALUES ('EL',2210,'spa','Falso Norte',NULL);
INSERT INTO label VALUES ('EL',2220,'spa','Unidades del falso Norte y falso Este',NULL);
INSERT INTO label VALUES ('EL',2230,'spa','Factor de escala en el Ecuador',NULL);
INSERT INTO label VALUES ('EL',2240,'spa','Altura del punto de vista del observador, en metros',NULL);
INSERT INTO label VALUES ('EL',2250,'spa','Longitud del centro de proyección',NULL);
INSERT INTO label VALUES ('EL',2260,'spa','Latitud en el centro de la proyeción',NULL);
INSERT INTO label VALUES ('EL',2270,'spa','Factor de escala en el centro de la línea',NULL);
INSERT INTO label VALUES ('EL',2280,'spa','Longitud vertical recta desde el Polo',NULL);
INSERT INTO label VALUES ('EL',2290,'spa','Factor de escala en el origen de la proyeción',NULL);
INSERT INTO label VALUES ('EL',2300,'spa','Rol: parámetro del Azimut de la línea oblicua',NULL);
INSERT INTO label VALUES ('EL',2310,'spa','Role_name:_obliqueLinePointParameter',NULL);
INSERT INTO label VALUES ('EL',2320,'spa','Contendos',NULL);
INSERT INTO label VALUES ('EL',2330,'spa','Descripción del Catálogo de Fenómenos',NULL);
INSERT INTO label VALUES ('EL',2340,'spa','Código de conformidad',NULL);
INSERT INTO label VALUES ('EL',2350,'spa','lenguaje',NULL);
INSERT INTO label VALUES ('EL',2360,'spa','Incluido en el conjunto de datos',NULL);
INSERT INTO label VALUES ('EL',2370,'spa','Fenómenos',NULL);
INSERT INTO label VALUES ('EL',2380,'spa','Catálogo de Fenómenos',NULL);
INSERT INTO label VALUES ('EL',2390,'spa','Descripción de la cobertura',NULL);
INSERT INTO label VALUES ('EL',2400,'spa','Descricpción de los atributos',NULL);
INSERT INTO label VALUES ('EL',2410,'spa','Tipo de elementos',NULL);
INSERT INTO label VALUES ('EL',2411,'spa','MD_CoverageContentTypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',2412,'spa','MD_CoverageContentTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',2420,'spa','dimensión',NULL);
INSERT INTO label VALUES ('EL',2430,'spa','Descripción de la imagen',NULL);
INSERT INTO label VALUES ('EL',2440,'spa','Ángulo de elevación del punto de iluminación',NULL);
INSERT INTO label VALUES ('EL',2450,'spa','Dirección del ángulo de iluminación',NULL);
INSERT INTO label VALUES ('EL',2460,'spa','Particularidades de la imagen',NULL);
INSERT INTO label VALUES ('EL',2461,'spa','MD_ImagingConditionCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',2462,'spa','MD_ImagingConditionCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',2470,'spa','Código de calidad de la imagen',NULL);
INSERT INTO label VALUES ('EL',2480,'spa','Porcentaje de nubosidad',NULL);
INSERT INTO label VALUES ('EL',2490,'spa','Código del nivel de proceso',NULL);
INSERT INTO label VALUES ('EL',2500,'spa','Cantidad de compresión',NULL);
INSERT INTO label VALUES ('EL',2510,'spa','Indicador de triangulación',NULL);
INSERT INTO label VALUES ('EL',2520,'spa','Disponibilidad de datos sobre la calibración radiomética',NULL);
INSERT INTO label VALUES ('EL',2530,'spa','Disponibilidad de información sobre la calibración de la cámara',NULL);
INSERT INTO label VALUES ('EL',2540,'spa','Disponiblilidad de información de distorsiones de la película',NULL);
INSERT INTO label VALUES ('EL',2550,'spa','Disponibilidad de información sobre la distorsión de las lentes',NULL);
INSERT INTO label VALUES ('EL',2560,'spa','MD_RangeDimension',NULL);
INSERT INTO label VALUES ('EL',2570,'spa','sequenceIdentifier',NULL);
INSERT INTO label VALUES ('EL',2580,'spa','descriptor',NULL);
INSERT INTO label VALUES ('EL',2590,'spa','Banda',NULL);
INSERT INTO label VALUES ('EL',2600,'spa','Valor máximo',NULL);
INSERT INTO label VALUES ('EL',2610,'spa','Valor mínimo',NULL);
INSERT INTO label VALUES ('EL',2620,'spa','Unidades',NULL);
INSERT INTO label VALUES ('EL',2630,'spa','Pico de respuesta',NULL);
INSERT INTO label VALUES ('EL',2640,'spa','Bits por valor',NULL);
INSERT INTO label VALUES ('EL',2650,'spa','Gradación del tono',NULL);
INSERT INTO label VALUES ('EL',2660,'spa','Factor de escala',NULL);
INSERT INTO label VALUES ('EL',2670,'spa','Offset (desplazamiento)',NULL);
INSERT INTO label VALUES ('EL',2680,'spa','MD_PortrayalCatalogueReference',NULL);
INSERT INTO label VALUES ('EL',2690,'spa','Catálogo de representación',NULL);
INSERT INTO label VALUES ('EL',2700,'spa','Distribución',NULL);
INSERT INTO label VALUES ('EL',2710,'spa','Formato de distribución',NULL);
INSERT INTO label VALUES ('EL',2720,'spa','Distribuidor',NULL);
INSERT INTO label VALUES ('EL',2730,'spa','Opciones de transferencia',NULL);
INSERT INTO label VALUES ('EL',2740,'spa','Opciones de transferencia digital',NULL);
INSERT INTO label VALUES ('EL',2750,'spa','Unidades de distribución',NULL);
INSERT INTO label VALUES ('EL',2760,'spa','Tamaño de transferencia',NULL);
INSERT INTO label VALUES ('EL',2770,'spa','Fuentes en línea',NULL);
INSERT INTO label VALUES ('EL',2780,'spa','Soportes fuera de línea',NULL);
INSERT INTO label VALUES ('EL',2790,'spa','Distribuidor',NULL);
INSERT INTO label VALUES ('EL',2800,'spa','Distribuidor',NULL);
INSERT INTO label VALUES ('EL',2810,'spa','Proceso de distribución',NULL);
INSERT INTO label VALUES ('EL',2820,'spa','Formato de distribución',NULL);
INSERT INTO label VALUES ('EL',2830,'spa','Opciones de tranferencia de distribución',NULL);
INSERT INTO label VALUES ('EL',2840,'spa','Formato',NULL);
INSERT INTO label VALUES ('EL',2850,'spa','Nombre del formato',NULL);
INSERT INTO label VALUES ('EL',2860,'spa','Versión',NULL);
INSERT INTO label VALUES ('EL',2870,'spa','Número de la revisión',NULL);
INSERT INTO label VALUES ('EL',2880,'spa','especificación',NULL);
INSERT INTO label VALUES ('EL',2890,'spa','Técncia de descompresión de ficheros',NULL);
INSERT INTO label VALUES ('EL',2900,'spa','Formato del distribuidor',NULL);
INSERT INTO label VALUES ('EL',2910,'spa','MD_Medium',NULL);
INSERT INTO label VALUES ('EL',2920,'spa','Nombre',NULL);
INSERT INTO label VALUES ('EL',2921,'spa','MD_MediumNameCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',2922,'spa','MD_MediumNameCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',2930,'spa','Densidad',NULL);
INSERT INTO label VALUES ('EL',2940,'spa','Densidad de las unidades de medida',NULL);
INSERT INTO label VALUES ('EL',2950,'spa','Volúmenes',NULL);
INSERT INTO label VALUES ('EL',2960,'spa','Formato del medio',NULL);
INSERT INTO label VALUES ('EL',2961,'spa','MD_MediumFormatCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',2962,'spa','MD_MediumFormatCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',2970,'spa','Observaciones del medio',NULL);
INSERT INTO label VALUES ('EL',2980,'spa','MD_StandardOrderProcess',NULL);
INSERT INTO label VALUES ('EL',2990,'spa','Tarifas',NULL);
INSERT INTO label VALUES ('EL',3000,'spa','Fecha y plazo de disponibilidad',NULL);
INSERT INTO label VALUES ('EL',3010,'spa','Instrucciones de pedido',NULL);
INSERT INTO label VALUES ('EL',3020,'spa','Tiempo de entrega',NULL);
INSERT INTO label VALUES ('EL',3030,'spa','MD_MetadataExtensionInformation',NULL);
INSERT INTO label VALUES ('EL',3040,'spa','Recurso en línea de la extensión',NULL);
INSERT INTO label VALUES ('EL',3050,'spa','Información de los elementos de la extensión',NULL);
INSERT INTO label VALUES ('EL',3060,'spa','MD_ExtendedElementInformation',NULL);
INSERT INTO label VALUES ('EL',3070,'spa','nombre',NULL);
INSERT INTO label VALUES ('EL',3080,'spa','Nombre abreviado',NULL);
INSERT INTO label VALUES ('EL',3090,'spa','código',NULL);
INSERT INTO label VALUES ('EL',3100,'spa','definición',NULL);
INSERT INTO label VALUES ('EL',3110,'spa','obligación',NULL);
INSERT INTO label VALUES ('EL',3111,'spa','MD_ObligationCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',3112,'spa','MD_ObligationCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',3120,'spa','condición',NULL);
INSERT INTO label VALUES ('EL',3130,'spa','Tipo de datos',NULL);
INSERT INTO label VALUES ('EL',3131,'spa','MD_DatatypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',3132,'spa','MD_DatatypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',3140,'spa','Máxima ocurrencia',NULL);
INSERT INTO label VALUES ('EL',3150,'spa','Domnio de valores',NULL);
INSERT INTO label VALUES ('EL',3160,'spa','Entidad padre',NULL);
INSERT INTO label VALUES ('EL',3170,'spa','regla',NULL);
INSERT INTO label VALUES ('EL',3180,'spa','motivo',NULL);
INSERT INTO label VALUES ('EL',3190,'spa','fuente',NULL);
INSERT INTO label VALUES ('EL',3200,'spa','Esquema de Aplicación',NULL);
INSERT INTO label VALUES ('EL',3210,'spa','nombre',NULL);
INSERT INTO label VALUES ('EL',3220,'spa','Lenguaje del Esquema',NULL);
INSERT INTO label VALUES ('EL',3230,'spa','Lenguaje de las Restircciones',NULL);
INSERT INTO label VALUES ('EL',3240,'spa','Esquema ASCII',NULL);
INSERT INTO label VALUES ('EL',3250,'spa','Fichero gráfico',NULL);
INSERT INTO label VALUES ('EL',3260,'spa','Fichero de desarrollo de software',NULL);
INSERT INTO label VALUES ('EL',3261,'spa','Binario base 64',NULL);
INSERT INTO label VALUES ('EL',3262,'spa','Binario hexadecimal',NULL);
INSERT INTO label VALUES ('EL',3263,'spa','Binario',NULL);
INSERT INTO label VALUES ('EL',3270,'spa','Formato del fichero de desarrollo de software',NULL);
INSERT INTO label VALUES ('EL',3340,'spa','Extensión',NULL);
INSERT INTO label VALUES ('EL',3350,'spa','Descripción',NULL);
INSERT INTO label VALUES ('EL',3360,'spa','Elemento geográfico',NULL);
INSERT INTO label VALUES ('EL',3370,'spa','Elemento temporal',NULL);
INSERT INTO label VALUES ('EL',3380,'spa','Elemento vertical',NULL);
INSERT INTO label VALUES ('EL',3390,'spa','Extensión geográfica',NULL);
INSERT INTO label VALUES ('EL',3400,'spa','Código del tipo de extensión',NULL);
INSERT INTO label VALUES ('EL',3410,'spa','Polígono envolvente',NULL);
INSERT INTO label VALUES ('EL',3420,'spa','polígono',NULL);
INSERT INTO label VALUES ('EL',3430,'spa','Rectángulo envolvente geográfico',NULL);
INSERT INTO label VALUES ('EL',3440,'spa','Longitud del límite Oeste',NULL);
INSERT INTO label VALUES ('EL',3450,'spa','Longitud del límite Este',NULL);
INSERT INTO label VALUES ('EL',3460,'spa','Latitud del límite Sur',NULL);
INSERT INTO label VALUES ('EL',3470,'spa','Latitud del límite Norte',NULL);
INSERT INTO label VALUES ('EL',3480,'spa','Descripción geográfica',NULL);
INSERT INTO label VALUES ('EL',3490,'spa','identificador geográfico',NULL);
INSERT INTO label VALUES ('EL',3500,'spa','Extensión temporal',NULL);
INSERT INTO label VALUES ('EL',3510,'spa','Extensión',NULL);
INSERT INTO label VALUES ('EL',3520,'spa','Extensión espacio-temporal',NULL);
INSERT INTO label VALUES ('EL',3530,'spa','Extensión espacial',NULL);
INSERT INTO label VALUES ('EL',3540,'spa','Extensión vertical',NULL);
INSERT INTO label VALUES ('EL',3550,'spa','Valor mínimo',NULL);
INSERT INTO label VALUES ('EL',3560,'spa','Valor máximo',NULL);
INSERT INTO label VALUES ('EL',3570,'spa','Unidades de medida',NULL);
INSERT INTO label VALUES ('EL',3580,'spa','Datum vertical',NULL);
INSERT INTO label VALUES ('EL',3581,'spa','Identificador del Datum',NULL);
INSERT INTO label VALUES ('EL',3582,'spa','responsable',NULL);
INSERT INTO label VALUES ('EL',3583,'spa','código',NULL);
INSERT INTO label VALUES ('EL',3584,'spa','Código del sitio',NULL);
INSERT INTO label VALUES ('EL',3590,'spa','Referencias',NULL);
INSERT INTO label VALUES ('EL',3600,'spa','Nombre',NULL);
INSERT INTO label VALUES ('EL',3601,'spa','nombre',NULL);
INSERT INTO label VALUES ('EL',3610,'spa','Nombre alternativo',NULL);
INSERT INTO label VALUES ('EL',3620,'spa','Fecha',NULL);
INSERT INTO label VALUES ('EL',3630,'spa','Edición',NULL);
INSERT INTO label VALUES ('EL',3640,'spa','Fecha de edición',NULL);
INSERT INTO label VALUES ('EL',3650,'spa','Indetificador',NULL);
INSERT INTO label VALUES ('EL',3670,'spa','Responsable',NULL);
INSERT INTO label VALUES ('EL',3680,'spa','Froma de presentación',NULL);
INSERT INTO label VALUES ('EL',3681,'spa','CI_PresentationFormCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',3682,'spa','CI_PresentationFormCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',3690,'spa','Serie',NULL);
INSERT INTO label VALUES ('EL',3700,'spa','Otros detalles',NULL);
INSERT INTO label VALUES ('EL',3710,'spa','Título colectivo',NULL);
INSERT INTO label VALUES ('EL',3720,'spa','ISBN',NULL);
INSERT INTO label VALUES ('EL',3730,'spa','ISSN',NULL);
INSERT INTO label VALUES ('EL',3740,'spa','Parte responsable',NULL);
INSERT INTO label VALUES ('EL',3750,'spa','Nombre',NULL);
INSERT INTO label VALUES ('EL',3760,'spa','Organismo',NULL);
INSERT INTO label VALUES ('EL',3770,'spa','Nombre del puesto',NULL);
INSERT INTO label VALUES ('EL',3780,'spa','Información del contacto',NULL);
INSERT INTO label VALUES ('EL',3790,'spa','función',NULL);
INSERT INTO label VALUES ('EL',3791,'spa','CI_RoleCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',3792,'spa','CI_RoleCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',3800,'spa','Dirección',NULL);
INSERT INTO label VALUES ('EL',3801,'spa','id',NULL);
INSERT INTO label VALUES ('EL',3810,'spa','Dirección de sumnistro',NULL);
INSERT INTO label VALUES ('EL',3820,'spa','ciudad',NULL);
INSERT INTO label VALUES ('EL',3830,'spa','Área administrativa',NULL);
INSERT INTO label VALUES ('EL',3840,'spa','Código Postal',NULL);
INSERT INTO label VALUES ('EL',3850,'spa','país',NULL);
INSERT INTO label VALUES ('EL',3860,'spa','e-mail',NULL);
INSERT INTO label VALUES ('EL',3870,'spa','CI_Contact',NULL);
INSERT INTO label VALUES ('EL',3880,'spa','teléfono',NULL);
INSERT INTO label VALUES ('EL',3890,'spa','Dirección',NULL);
INSERT INTO label VALUES ('EL',3900,'spa','Recurso en línea',NULL);
INSERT INTO label VALUES ('EL',3910,'spa','Horario de servicio',NULL);
INSERT INTO label VALUES ('EL',3920,'spa','Información adicional',NULL);
INSERT INTO label VALUES ('EL',3930,'spa','CI_Date',NULL);
INSERT INTO label VALUES ('EL',3940,'spa','fecha',NULL);
INSERT INTO label VALUES ('EL',3950,'spa','Tipo de fecha',NULL);
INSERT INTO label VALUES ('EL',3951,'spa','CI_DateTypeCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',3952,'spa','CI_DateTypeCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',3960,'spa','CI_OnlineResource',NULL);
INSERT INTO label VALUES ('EL',3970,'spa','enlace',NULL);
INSERT INTO label VALUES ('EL',3980,'spa','protocolo',NULL);
INSERT INTO label VALUES ('EL',3990,'spa','Perfil de la aplicación',NULL);
INSERT INTO label VALUES ('EL',4000,'spa','nombre',NULL);
INSERT INTO label VALUES ('EL',4010,'spa','descripción',NULL);
INSERT INTO label VALUES ('EL',4020,'spa','función',NULL);
INSERT INTO label VALUES ('EL',4021,'spa','CI_OnLineFunctionCode_CodeList',NULL);
INSERT INTO label VALUES ('EL',4022,'spa','CI_OnLineFunctionCode_DomainCodes',NULL);
INSERT INTO label VALUES ('EL',4030,'spa','CI_Series',NULL);
INSERT INTO label VALUES ('EL',4040,'spa','Nombre',NULL);
INSERT INTO label VALUES ('EL',4050,'spa','Identificación del tema de la serie',NULL);
INSERT INTO label VALUES ('EL',4060,'spa','página',NULL);
INSERT INTO label VALUES ('EL',4070,'spa','CI_Telephone',NULL);
INSERT INTO label VALUES ('EL',4080,'spa','voz',NULL);
INSERT INTO label VALUES ('EL',4090,'spa','Fax',NULL);
INSERT INTO label VALUES ('EL',5001,'spa','Comienzo + Final',NULL);
INSERT INTO label VALUES ('EL',5002,'spa','Comienzo + Rango',NULL);
INSERT INTO label VALUES ('EL',5003,'spa','Fin + Rango',NULL);
INSERT INTO label VALUES ('EL',5004,'spa','Instante',NULL);
INSERT INTO label VALUES ('EL',5005,'spa','comienzo',NULL);
INSERT INTO label VALUES ('EL',5006,'spa','final',NULL);
INSERT INTO label VALUES ('EL',5007,'spa','duración',NULL);
INSERT INTO label VALUES ('EL',5010,'spa','valor',NULL);
INSERT INTO label VALUES ('EL',5011,'spa','exactitud',NULL);
INSERT INTO label VALUES ('EL',5012,'spa','Unidades de medida',NULL);
INSERT INTO label VALUES ('EL',5013,'spa','Nombre de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5014,'spa','Símbolo de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5015,'spa','Nombre de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5016,'spa','Símbolo de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5017,'spa','Nombre de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5018,'spa','Símbolo de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5019,'spa','Nombre de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5020,'spa','Símbolo de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5021,'spa','Nombre de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5022,'spa','Símbolo de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5023,'spa','Nombre de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5024,'spa','Símbolo de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5025,'spa','Nombre de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5026,'spa','Símbolo de la unidad de medida',NULL);
INSERT INTO label VALUES ('EL',5050,'spa','Otro valor',NULL);
INSERT INTO label VALUES ('EL',5051,'spa','Valor de registros',NULL);
INSERT INTO label VALUES ('EL',5052,'spa','atributos',NULL);
INSERT INTO label VALUES ('EL',5053,'spa','Tipo de registro',NULL);
INSERT INTO label VALUES ('EL',5054,'spa','Nombre del Atributo',NULL);
INSERT INTO label VALUES ('EL',5055,'spa','Cualquiera',NULL);
INSERT INTO label VALUES ('EL',5101,'spa','instante',NULL);
INSERT INTO label VALUES ('EL',5102,'spa','comienzo / final',NULL);
INSERT INTO label VALUES ('EL',5103,'spa','comienzo',NULL);
INSERT INTO label VALUES ('EL',5104,'spa','final',NULL);
INSERT INTO label VALUES ('EL',5105,'spa','fecha',NULL);
INSERT INTO label VALUES ('EL',6001,'spa','ayuda',NULL);
INSERT INTO label VALUES ('EL',6010,'spa','acquisitionInformation',NULL);
INSERT INTO label VALUES ('EL',6020,'spa','MI_AcquisitionInformation',NULL);
INSERT INTO label VALUES ('EL',6021,'spa','platform',NULL);
INSERT INTO label VALUES ('EL',6040,'spa','MI_Platform',NULL);
INSERT INTO label VALUES ('EL',6041,'spa','instrument',NULL);
INSERT INTO label VALUES ('EL',6060,'spa','MI_Instrument',NULL);
INSERT INTO label VALUES ('EL',7001,'spa','id',NULL);
INSERT INTO label VALUES ('EL',10001,'spa','título',NULL);
INSERT INTO label VALUES ('EL',10002,'spa','creador',NULL);
INSERT INTO label VALUES ('EL',10003,'spa','materia',NULL);
INSERT INTO label VALUES ('EL',10004,'spa','descripción',NULL);
INSERT INTO label VALUES ('EL',10005,'spa','publicador',NULL);
INSERT INTO label VALUES ('EL',10006,'spa','contribuidor',NULL);
INSERT INTO label VALUES ('EL',10007,'spa','Fecha',NULL);
INSERT INTO label VALUES ('EL',10008,'spa','tipo',NULL);
INSERT INTO label VALUES ('EL',10009,'spa','formato',NULL);
INSERT INTO label VALUES ('EL',10010,'spa','identificaor',NULL);
INSERT INTO label VALUES ('EL',10011,'spa','fuente',NULL);
INSERT INTO label VALUES ('EL',10012,'spa','lenguaje',NULL);
INSERT INTO label VALUES ('EL',10013,'spa','relación',NULL);
INSERT INTO label VALUES ('EL',10014,'spa','Cobertura',NULL);
INSERT INTO label VALUES ('EL',10015,'spa','Derechos',NULL);
INSERT INTO label VALUES ('EL',20000,'spa','Catálogo de Fenómenos',NULL);
INSERT INTO label VALUES ('EL',20001,'spa','Nombre',NULL);
INSERT INTO label VALUES ('EL',20002,'spa','Ámbito',NULL);
INSERT INTO label VALUES ('EL',20003,'spa','Campo de aplicación',NULL);
INSERT INTO label VALUES ('EL',20004,'spa','Número de versión',NULL);
INSERT INTO label VALUES ('EL',20005,'spa','Fecha de la versión',NULL);
INSERT INTO label VALUES ('EL',20006,'spa','Definición de la fuente',NULL);
INSERT INTO label VALUES ('EL',20007,'spa','Tipo de definición',NULL);
INSERT INTO label VALUES ('EL',20008,'spa','Productor',NULL);
INSERT INTO label VALUES ('EL',20009,'spa','Lenguaje funcional',NULL);
INSERT INTO label VALUES ('EL',20010,'spa','Tipo de fenómeno',NULL);
INSERT INTO label VALUES ('EL',20011,'spa','Nombre del tipo',NULL);
INSERT INTO label VALUES ('EL',20012,'spa','Definición',NULL);
INSERT INTO label VALUES ('EL',20013,'spa','Código',NULL);
INSERT INTO label VALUES ('EL',20014,'spa','Alias',NULL);
INSERT INTO label VALUES ('EL',20019,'spa','Valor del atributo',NULL);
INSERT INTO label VALUES ('EL',20020,'spa','idioma',NULL);
INSERT INTO label VALUES ('EL',20021,'spa','Código del Lenguaje',NULL);
INSERT INTO label VALUES ('EL',20030,'spa','Atributo del fenómeno',NULL);
INSERT INTO label VALUES ('EL',20031,'spa','Nombre del atributo',NULL);
INSERT INTO label VALUES ('EL',20032,'spa','Definición',NULL);
INSERT INTO label VALUES ('EL',20033,'spa','Código',NULL);
INSERT INTO label VALUES ('EL',20034,'spa','Tipo de dato',NULL);
INSERT INTO label VALUES ('EL',20035,'spa','Unidad de medida',NULL);
INSERT INTO label VALUES ('EL',20036,'spa','Tipo de dominio',NULL);
INSERT INTO label VALUES ('EL',20037,'spa','Valores del dominio',NULL);
INSERT INTO label VALUES ('EL',20038,'spa','Etiqueta',NULL);
INSERT INTO label VALUES ('EL',20039,'spa','Código',NULL);
INSERT INTO label VALUES ('EL',20040,'spa','Definición',NULL);
INSERT INTO label VALUES ('EL',20041,'spa','Cardinalidad',NULL);
INSERT INTO label VALUES ('EL',23740,'spa','Responsible Party',NULL);
INSERT INTO label VALUES ('EL',23800,'spa','Address',NULL);
INSERT INTO label VALUES ('EL',23870,'spa','CI_Contact',NULL);
INSERT INTO label VALUES ('EL',23960,'spa','CI_OnlineResource',NULL);
INSERT INTO label VALUES ('EL',24070,'spa','CI_Telephone',NULL);
INSERT INTO label VALUES ('EL',30001,'spa','Tipo de servicio',NULL);
INSERT INTO label VALUES ('EL',30002,'spa','Versión de tipo de servicio',NULL);
INSERT INTO label VALUES ('EL',30003,'spa','Propiedades de Accesos',NULL);
INSERT INTO label VALUES ('EL',30004,'spa','Restricciones',NULL);
INSERT INTO label VALUES ('EL',30008,'spa','Operaciones Comprendidas',NULL);
INSERT INTO label VALUES ('EL',30009,'spa','Opera sobre',NULL);
INSERT INTO label VALUES ('EL',30011,'spa','Nombre del valor',NULL);
INSERT INTO label VALUES ('EL',30012,'spa','Nombre del Namespace',NULL);
INSERT INTO label VALUES ('EL',30020,'spa','xlink:href',NULL);
INSERT INTO label VALUES ('EL',30021,'spa','xlink:type',NULL);
INSERT INTO label VALUES ('EL',30100,'spa','SV_OperationMetadata',NULL);
INSERT INTO label VALUES ('EL',30101,'spa','Nombre de la operación',NULL);
INSERT INTO label VALUES ('EL',30102,'spa','DCP',NULL);
INSERT INTO label VALUES ('EL',30103,'spa','Descripción de la operación',NULL);
INSERT INTO label VALUES ('EL',30104,'spa','Nombre de invocación',NULL);
INSERT INTO label VALUES ('EL',30105,'spa','Parámetros',NULL);
INSERT INTO label VALUES ('EL',30106,'spa','Punto de conexión',NULL);
INSERT INTO label VALUES ('EL',30107,'spa','Depenede de',NULL);
INSERT INTO label VALUES ('EL',30200,'spa','Tipo de acoplamiento',NULL);
INSERT INTO label VALUES ('EL',30210,'spa','CSW_CouplingType',NULL);
INSERT INTO label VALUES ('EL',30300,'spa','Recurso adjunto',NULL);
INSERT INTO label VALUES ('EL',30310,'spa','SV_CoupledResource',NULL);
INSERT INTO label VALUES ('EL',30320,'spa','Nombre controlado',NULL);
INSERT INTO label VALUES ('MB',0,'spa','Metadatos',NULL);
INSERT INTO label VALUES ('MB',1,'spa','Identificación de los Datos',NULL);
INSERT INTO label VALUES ('MB',2,'spa','Restricciones de los metadatos',NULL);
INSERT INTO label VALUES ('MB',3,'spa','Calidad de los datos',NULL);
INSERT INTO label VALUES ('MB',4,'spa','Mantenimiento de los Metadatos',NULL);
INSERT INTO label VALUES ('MB',5,'spa','Representación espacial',NULL);
INSERT INTO label VALUES ('MB',6,'spa','Sistema de Referencia',NULL);
INSERT INTO label VALUES ('MB',7,'spa','Contenidos',NULL);
INSERT INTO label VALUES ('MB',8,'spa','Catálogo de representación',NULL);
INSERT INTO label VALUES ('MB',9,'spa','Distribución',NULL);
INSERT INTO label VALUES ('MB',10,'spa','Extensión de los Metadatos',NULL);
INSERT INTO label VALUES ('MB',11,'spa','Esquema de Aplicación',NULL);
INSERT INTO label VALUES ('MB',12,'spa','Dublin Core',NULL);
INSERT INTO label VALUES ('MB',13,'spa','Catálogo de Fenómenos',NULL);
INSERT INTO label VALUES ('PN',0,'spa','Todo ISO 19115',NULL);
INSERT INTO label VALUES ('PN',1,'spa','Obligatorio en ISO 19115',NULL);
INSERT INTO label VALUES ('PN',2,'spa','Núcleo de ISO 19115',NULL);
INSERT INTO label VALUES ('PN',3,'spa','DC / ISO',NULL);
INSERT INTO label VALUES ('PN',4,'spa','ISO 19115 INSPIRE',NULL);
INSERT INTO label VALUES ('PN',7,'spa','Micka',NULL);
INSERT INTO label VALUES ('PN',100,'spa','Todo ISO 19119',NULL);
INSERT INTO label VALUES ('PN',101,'spa','Obligatorio en ISO 19119',NULL);
INSERT INTO label VALUES ('PN',102,'spa','Núcleo de ISO 19119',NULL);
INSERT INTO label VALUES ('PN',103,'spa','DC / ISO',NULL);
INSERT INTO label VALUES ('PN',104,'spa','ISO 19119 INSPIRE',NULL);
INSERT INTO label VALUES ('PN',107,'spa','Micka',NULL);
INSERT INTO label VALUES ('SD',0,'spa','Spatial Data Metadata (ISO 19115)',NULL);
INSERT INTO label VALUES ('SD',1,'spa','Metadatos (Dublin Core)',NULL);
INSERT INTO label VALUES ('SD',2,'spa','Catálogo de Fenómenos',NULL);
INSERT INTO label VALUES ('SD',10,'spa','Service Metadata (ISO 19119)',NULL);
INSERT INTO label VALUES ('SD',99,'spa','Importar de fichero / URL',NULL);
